### ISSUE TITLE
App.on_pause / on_resume on iOS not called properly?

### ISSUE THREAD

**Issue by rnixx** [kivy/kivy#3202]
It seems that on_pause/on_resume is not called properly on iOS (iPad mini with iOS 8.2).

Neither when leaving the app via home button, nor when pressing power button on_pause is called, on_resume is not called either when reentering the application.

Any hints?

**Comment by kmonson** [comment]
I'll second this. I've seen in in the simulator (iOS 6 and 8) and on an Ipad running 7.0. on_stop does not appear to be called either.

**Comment by rnixx** [comment]
Hi, any new insights on this?

**Comment by rnixx** [comment]
@dessant on android pause and resume events work fine for me. have you encountered this issue on android as well?

And referring iOS. Anybody with the required knowledge motivated to take a look about this?

**Comment by thica** [comment]
I can confim, that on Android 5 the on_resume is called very unreliable. It's called most of the time, but not every time. I didn't had this issue with 4.4

**Comment by rnixx** [comment]
This issue may be related https://github.com/kivy/kivy/issues/1261

**Comment by rnixx** [comment]
The iOS App lifecycle, states and corresponding events are documented here
https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/TheAppLifeCycle/TheAppLifeCycle.html#//apple_ref/doc/uid/TP40007072-CH2-SW3

I greped my project and kivy-ios for those events but cannot find anything.

Where does the code for bridging iOS lifecycle events to kivy lifes? Is it implemented at all?

**Comment by dessant** [comment]
@rnixx somebody on irc reported the same issue on android iirc.

**Comment by rnixx** [comment]
now i tried to react as delegate via pyobjus directly. The code looks something like:

    if platform == 'ios':
        from pyobjus import protocol

        class IOSPlatformMixin(PlatformMixin):

            @protocol('NSApplicationDelegate.applicationDidBecomeActive')
            def app_did_become_active(self, *args, **kw):
                Logger.debug('IOSPlatformMixin.app_did_become_active')

            @protocol('NSApplicationDelegate.applicationWillResignActive')
            def app_will_resign_active(self, *args, **kw):
                Logger.debug('IOSPlatformMixin.app_will_resign_active')

        PlatformMixin = IOSPlatformMixin

    class MyApp(App, PlatformMixin):
        ...

But i cannot get this work either. How do i correctly setup the app lifecycle delegates?

**Comment by tito** [comment]
I don't think adding specific delegates will work, we are using SDL2, and so, we need to double-check why SDL2 doesn't send the events at all. Or if we correctly manage them or not.

**Comment by tito** [comment]
Ok, we completly missed thoses when switching to SDL2:

SDL_APP_TERMINATING
OS is terminating the application
SDL_APP_LOWMEMORY
OS is low on memory; free some
SDL_APP_WILLENTERBACKGROUND
application is entering background
SDL_APP_DIDENTERBACKGROUND
application entered background
SDL_APP_WILLENTERFOREGROUND
application is entering foreground
SDL_APP_DIDENTERFOREGROUND
application entered foreground

Will add them and test it right now.

**Comment by tito** [comment]
Reference: https://wiki.libsdl.org/SDL_EventType

**Comment by tito** [comment]
So weird. Even without implementing theses event, i can actually pause/resume the pictures demo. I see the vent called.

Currently, pause/resume are implemented on the window minimzed/restored. We could change to will enter background/foreground for android/ios, but still, i don't get the issue on iPad 2 simulator, iPad 3 real device, both iOS 8.2. Checking iPad mini air on iOS 8.4 in simulator.

**Comment by tito** [comment]
Ok no, my bad, i did change the implementation. One change in kivy for minimizing the app did break this behavior. Fixing it;

**Comment by tito** [comment]
You need to use kivy master, not kivy 1.9.0 when compiling (1.9.0 is the default in the recipe). Enjoy!

**Comment by kmonson** [comment]
Huzzah!

Thanks tito!

**Comment by rnixx** [comment]
Thanks!

**Comment by kmonson** [comment]
I think you've got a bad copy paste:

+        elif event.type == SDL_APP_WILLENTERBACKGROUND:
+            return ('app_willenterbackground', )
+        elif event.type == SDL_APP_DIDENTERBACKGROUND:
+            return ('app_didenterbackground', )
+        elif event.type == SDL_APP_WILLENTERFOREGROUND:
+            return ('app_willenterforeground', )
+        elif event.type == SDL_APP_DIDENTERBACKGROUND:
+            return ('app_didenterbackground', )

SDL_APP_DIDENTERBACKGROUND is repeated twice and SDL_APP_DIDENTERFOREGROUND is missing I think.

**Comment by kmonson** [comment]
The return statement needs to be fixed as well for the same reason.

**Comment by tito** [comment]
Fixed, thanks for your eyes ^^

**Comment by rnixx** [comment]
Unfortunately the behavior is still not correct on iOS (tested on ipad mini with ios 8.3)

* When pressing the home button, on_pause and on_resume work as expected.
* When pressing device lock, the device goes to sleep immediately and nothing is called.
* When unlocking the device on_pause is called instead of on_resume.

@kmonson can you confirm this? or anybody else?

**Comment by rnixx** [comment]
For me this looks like a timing problem and the app not receives the event before going into sleep or similar. pause event on emulator happens somewhat deferred. Also https://github.com/kivy/kivy/blob/master/kivy/core/window/window_sdl2.py#L542 might be related to the whole story

**Comment by rnixx** [comment]
can someone reopen this please?

**Comment by rnixx** [comment]
The related SDL documentation (https://wiki.libsdl.org/SDL_EventType) says:

"These events must be handled in an event filter, since often the OS needs an immediate response and will terminate your process shortly after sending the event, and if it sits in the SDL event queue, it'll be too late."

and

"You can handle everything else through a normal SDL_PollEvent() loop, but you should set up a callback with SDL_SetEventFilter() for these specific events."

grep'ing kivy for SDL_PollEvent and SDL_SetEventFilter tells me:

    ~/workspace/kivy/kivy$ grep -rnI 'SDL_PollEvent' .
    ./core/window/_window_sdl2.pyx:201:        if SDL_PollEvent(&event) == 0:
    ./core/window/_window_sdl2.c:3389: *         if SDL_PollEvent(&event) == 0:             # <<<<<<<<<<<<<<
    ./core/window/_window_sdl2.c:3393:  __pyx_t_1 = ((SDL_PollEvent((&__pyx_v_event)) == 0) != 0);
    ./core/window/_window_sdl2.c:3398: *         if SDL_PollEvent(&event) == 0:
    ./lib/sdl2.pxi:468:    cdef int SDL_PollEvent(SDL_Event * event)
    ~/workspace/kivy/kivy$ grep -rnI 'SDL_SetEventFilter' .

Looks like the event fileter callback is missing for the lifecycle events
rnix@blackbox:~/workspace/kivy/kivy$

**Comment by rnixx** [comment]
That's what i found in the SDL sources https://hg.libsdl.org/SDL/file/704a0bfecf75/README-ios.txt#l58

**Comment by rnixx** [comment]
Here i began to integrate SDL_EventFilter https://github.com/rnixx/kivy/commit/ce871ee3d9ae1b068b1632b9c004cc5b4d76393a. Took me some time with my rudimentary cython skills, but maybe it saves you some minutes ;)

**Comment by marystern** [comment]
Hi @tito,

I have the same problem on Android 5.1 (ie on_pause() does not get called when it should).

I've just tried this again with current master (commit 0c7cd9ea95851fbe3bbf029a9832232a774fbd5a) 
and again with the patch from mixx above applied: in both cases this is still broken on Android.

My app is a simple one that uses the camera: it correctly calls out to the Android Camera app, but will not return due to this bug.

Here's a snippet of the logs, and I have logging in my on_pause/on_resume() methods which never get called (on_pause does return True by the way):
```
----
I/python  (13908): [INFO              ] [XXXXXXXX    ] === App STARTED =======================
I/python  (13908): [INFO              ] [OSC         ] using <thread> for socket
I/python  (13908): [INFO              ] [Base        ] Start application main loop
I/python  (13908): [INFO              ] [Android     ] found 17 joystick
I/python  (13908): [INFO              ] [Android     ] create joystick <0>
I/python  (13908): [INFO              ] [Android     ] discard joystick <0> cause no button
...
I/python  (13908): [INFO              ] [Android     ] create joystick <16>
I/ActivityManager(  472): START u0 {act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.google.android.GoogleCamera/com.android.camera.CaptureActivity (has clip) (has extras)} from uid 10155 on display 0
V/WindowManager(  472): addAppToken: AppWindowToken{3d8ce58c token=Token{25f1babf ActivityRecord{214aa8de u0 com.google.android.GoogleCamera/com.android.camera.CaptureActivity t45}}} to stack=1 task=45 at 1
I/python  (13908): [INFO              ] [Android     ] Must go into sleep mode, check the app
I/python  (13908): [INFO              ] [Android     ] App doesn't support pause mode, stop.
I/python  (13908): [INFO              ] [Base        ] Leaving application in progress...
I/python  (13908): [INFO              ] [XXXXXXXX    ] --- App STOPPED =======================
----
```

I've been struggling for a while to get the camera on Android working with Kivy (not easy), and this bug is the latest blocker..can you re-open this issue please? Thanks.

**Comment by tito** [comment]
Please open a new issue, this one for iOS is solved. If possible, give us a snippet to reproduce it.
