### ISSUE TITLE
Document xsel and xclip as dependencies on Linux

### ISSUE THREAD

**Issue by dessant** [kivy/kivy#4036]
I could not find a reference about them in the docs.

Is a cut buffer provider critical? Couldn't we just skip the feature when these deps are not present?

**Comment by janssen** [comment]
What's more, kivy/__init__.py/kivy_options doesn't have a "cutbuffer" section, so you can't override it with an environment variable.

**Comment by benelgiac** [comment]
Well, this still happens in kivy 1.10, at least for me so it probably should be solved

`[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'4.5.0 NVIDIA 28.1.0'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA Tegra X1 (nvgpu)/integrated'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 5
[INFO   ] [GL          ] Shading version <b'4.50 NVIDIA'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Clipboard   ] Provider: gtk3(['clipboard_dbusklipper'] ignored)
[CRITICAL] [Cutbuffer   ] Unable to find any valuable Cutbuffer provider.
xclip - FileNotFoundError: [Errno 2] No such file or directory: 'xclip'
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/lib/python3/dist-packages/kivy/core/clipboard/clipboard_xclip.py", line 17, in <module>
    p = subprocess.Popen(['xclip', '-version'], stdout=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)

xsel - FileNotFoundError: [Errno 2] No such file or directory: 'xsel'
  File "/usr/lib/python3/dist-packages/kivy/core/__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "/usr/lib/python3/dist-packages/kivy/core/clipboard/clipboard_xsel.py", line 16, in <module>
    p = subprocess.Popen(['xsel'], stdout=subprocess.PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
`

**Comment by vkrntgtm** [comment]
I am working on Kivy==1.10.1 and python==3.6. Same problem. Can it be solved???

**Comment by GeorgeCiesinski** [comment]
Kivy==1.11.1, Python 3.7, and I am also experiencing this issue. Odd, doesn't seem to affect my app, but it is concerning to see these errors.

**Comment by AndiEcker** [comment]
Same here on a fresh Ubuntu without the xsel/xclip apt-get packages.

Log (removed some irrelevant DEBUG message):

`[INFO   ] [Kivy        ] v1.11.1
[INFO   ] [Kivy        ] Installed at "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.6.9 (default, Aug 28 2019, 15:54:20) 
[GCC 7.4.0]
[INFO   ] [Python      ] Interpreter at "/home/andi/.pyenv/versions/kivy_env/bin/python"
[INFO   ] [Factory     ] 184 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[DEBUG  ] [Window      ] Ignored <egl_rpi> (import error)
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'3.0 Mesa 19.0.8'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Open Source Technology Center'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa DRI Intel(R) Ivybridge Mobile '>
[INFO   ] [GL          ] OpenGL parsed version: 3, 0
[INFO   ] [GL          ] Shading version <b'1.30'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[DEBUG  ] [Base        ] Create provider from mouse
[DEBUG  ] [Base        ] Create provider from probesysfs
[DEBUG  ] [ProbeSysfs  ] using probesysfs!
[DEBUG  ] [ProbeSysfs  ] found device: SynPS/2 Synaptics TouchPad at /dev/input/event8
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event8
[INFO   ] [MTD         ] Read event from </dev/input/event8>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [MTD         ] </dev/input/event8> range position X is 1268 - 5674
[INFO   ] [MTD         ] </dev/input/event8> range position Y is 1098 - 4754
[INFO   ] [MTD         ] </dev/input/event8> range touch major is 0 - 0
[INFO   ] [MTD         ] </dev/input/event8> range touch minor is 0 - 0
[INFO   ] [MTD         ] </dev/input/event8> range pressure is 0 - 255
[INFO   ] [MTD         ] </dev/input/event8> axes invertion: X is 0, Y is 0
[INFO   ] [MTD         ] </dev/input/event8> rotation set to 0
[INFO   ] [Clipboard   ] Provider: sdl2(['clipboard_xclip', 'clipboard_xsel', 'clipboard_dbusklipper', 'clipboard_gtk3'] ignored)
[CRITICAL] [Cutbuffer   ] Unable to find any valuable Cutbuffer provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
xclip - FileNotFoundError: [Errno 2] No such file or directory: 'xclip': 'xclip'
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/core/__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/core/clipboard/clipboard_xclip.py", line 17, in <module>
    p = subprocess.Popen(['xclip', '-version'], stdout=subprocess.PIPE)
  File "/home/andi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/andi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

xsel - FileNotFoundError: [Errno 2] No such file or directory: 'xsel': 'xsel'
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/core/__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/andi/.pyenv/versions/kivy_env/lib/python3.6/site-packages/kivy/core/clipboard/clipboard_xsel.py", line 16, in <module>
    p = subprocess.Popen(['xsel'], stdout=subprocess.PIPE)
  File "/home/andi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/andi/.pyenv/versions/3.6.9/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
`

**Comment by osm3000** [comment]
Same exact message for me as well

**Comment by jgirardet** [comment]
same thing. python 3.7 on kubuntu 19.10
also affects 2.0.0rc3

**Comment by elijahlau** [comment]
[INFO   ] [Clipboard   ] Provider: sdl2(['clipboard_xclip', 'clipboard_xsel', 'clipboard_dbusklipper', 'clipboard_gtk3'] ignored)
[CRITICAL] [Cutbuffer   ] Unable to find any valuable Cutbuffer provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
xclip - FileNotFoundError: [Errno 2] No such file or directory: 'xclip': 'xclip'
  File "/home/eli/Desktop/guess/venv/lib/python3.7/site-packages/kivy/core/__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/eli/Desktop/guess/venv/lib/python3.7/site-packages/kivy/core/clipboard/clipboard_xclip.py", line 17, in <module>
    p = subprocess.Popen(['xclip', '-version'], stdout=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

xsel - FileNotFoundError: [Errno 2] No such file or directory: 'xsel': 'xsel'
  File "/home/eli/Desktop/guess/venv/lib/python3.7/site-packages/kivy/core/__init__.py", line 63, in core_select_lib
    fromlist=[modulename], level=0)
  File "/home/eli/Desktop/guess/venv/lib/python3.7/site-packages/kivy/core/clipboard/clipboard_xsel.py", line 16, in <module>
    p = subprocess.Popen(['xsel'], stdout=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)



same for me

**Comment by jgirardet** [comment]
fixed with  apt -get install xclip
https://github.com/jgirardet/mydevoirs/blob/4bfb9bbaf547e06ccffd524effa3eab02a50109c/.github/workflows/test_and_build.yml#L39

**Comment by EliDutu** [comment]
sudo apt-get install -y xclip 
will fix it

**Comment by Shudh** [comment]
![image](https://user-images.githubusercontent.com/14231420/221776861-234af10c-5f65-4c9a-b4b9-09431ddf9fc1.png)
Well this still happens on 

Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

**Comment by beauxq** [comment]
This is still an issue.

If kivy depends on xsel and xclip, that installation should happen automatically when someone does `pip install kivy`

**Comment by misl6** [comment]
Hi @beauxq !

`Cutbuffer` is not essential, neither are `xclip` or `xsel`:
https://github.com/kivy/kivy/blob/cd4cb0f649c1d34503aba631e405f0c532aef48a/kivy/core/clipboard/__init__.py#L156-L157

Can you confirm that even if the critical error (which I agree is not great) is shown, the app works just fine?

**Comment by beauxq** [comment]
Yes, I see now. I had an app crash and I saw the xsel and xclip messages, and I thought they were related to the crash.
I see now that those messages are not related to the crash that I had.

**Comment by wileur** [comment]
Workaround for pure wayland installations where xsel and xclip are not available at all, like Yocto/Poky on imx8mm:

```
# Create fake xsel to make Kivy error message go away
# Run as root, and make sure you don't already have xsel installed, as it will be overwritten
echo "#!/bin/bash" > /usr/bin/xsel
chmod +x /usr/bin/xsel
```
This creates an empty, executable script that gets rid of the error message. It doesn't solve the copy/paste Cutbuffer issue. But my embedded device has no need for cut and paste.

The point is that Kivy is looking for anything executable named xsel, and will be very happy as long as it is in the path.

For simplicity in Yocto I put this script in the /etc/rc.local but it is enough to create it once.
