### ISSUE TITLE
Kivy not working after installation

### ISSUE THREAD

**Issue by sarmamen** [kivy/kivy#4115]
I was installing kivy for the first time:
`python -m pip install --upgrade pip wheel setuptools`

`python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew \
kivy.deps.gstreamer --extra-index-url https://kivy.org/downloads/packages/simple/`

`python -m pip install kivy`

but after i run:
```
from kivy.app import App
from kivy.uix.button import Button

class TestApp(App):
    def build(self):
        return Button(text='Hello World')

TestApp().run()
```
i would get

```
C:\Python27\python.exe "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 5.0.4\helpers\pycharm\utrunner.py" "C:\- Python_projekti\python_GUI_testiranje\testiranje.py" true
Testing started at 19:33 ...
[INFO              ] [Logger      ] Record log in C:\Users\Kyte\.kivy\logs\kivy_16-03-24_4.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
[INFO              ] [Text        ] Provider: sdl2
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <4.5.13399 Compatibility Profile Context 15.201.1151.1008>
[INFO              ] [GL          ] OpenGL vendor <ATI Technologies Inc.>
[INFO              ] [GL          ] OpenGL renderer <AMD Radeon R7 200 Series>
[INFO              ] [GL          ] OpenGL parsed version: 4, 5
[INFO              ] [GL          ] Shading version <4.40>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <32>
[WARNING           ] [Image       ] Unable to load image <C:\Python27\lib\site-packages\kivy\data\glsl\default.png>
[CRITICAL          ] [Window      ] Unable to find any valuable Window provider at all!
sdl2 - Exception: SDL2: Unable to load image
  File "C:\Python27\lib\site-packages\kivy\core\__init__.py", line 67, in core_select_lib
    cls = cls()
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 138, in __init__
    super(WindowSDL, self).__init__()
  File "C:\Python27\lib\site-packages\kivy\core\window\__init__.py", line 722, in __init__
    self.create_window()
  File "C:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 255, in create_window
    super(WindowSDL, self).create_window()
  File "C:\Python27\lib\site-packages\kivy\core\window\__init__.py", line 897, in create_window
    self.render_context = RenderContext()
  File "kivy\graphics\instructions.pyx", line 756, in kivy.graphics.instructions.RenderContext.__init__ (kivy\graphics\instructions.c:10729)
  File "C:\Python27\lib\site-packages\kivy\core\image\__init__.py", line 512, in __init__
    self.filename = arg
  File "C:\Python27\lib\site-packages\kivy\core\image\__init__.py", line 700, in _set_filename
    mipmap=self._mipmap, nocache=self._nocache)
  File "C:\Python27\lib\site-packages\kivy\core\image\__init__.py", line 430, in load
    im = loader(filename, **kwargs)
  File "C:\Python27\lib\site-packages\kivy\core\image\__init__.py", line 198, in __init__
    self._data = self.load(filename)
  File "C:\Python27\lib\site-packages\kivy\core\image\img_sdl2.py", line 42, in load
    raise Exception('SDL2: Unable to load image')
 
[CRITICAL          ] [App         ] Unable to get a Window, abort.
 Exception SystemExit: 1 in 'kivy.properties.dpi2px' ignored
[CRITICAL          ] [App         ] Unable to get a Window, abort.
 
Process finished with exit code 1
```
and i went to kivy IRC for help. two guys helped me out. i did:
`python -m pip uninstall pillow`
`python -m pip install --use-wheel pillow`

and after that i would run my app, but with some modification and it is working now
```
import os
os.environ['KIVY_IMAGE'] = 'pil,sdl2'
from kivy.app import App
from kivy.uix.button import Button

class TestApp(App):
    def build(self):
        return Button(text='Hello World')

TestApp().run()
```
One more time thank to **quanon** and **kived** from the IRC channel. They are the best :)

**Comment by matham** [comment]
I'm not exactly sure the point of this issue. This is very a likely a problem specific to that user's computer because it doesn't happen otherwise.

**Comment by rnixx** [comment]
It looks like you have a resource loading problem (whyever)

    File "C:\Python27\lib\site-packages\kivy\core\image\__init__.py", line 198, in __init__
        self._data = self.load(filename)
    File "C:\Python27\lib\site-packages\kivy\core\image\img_sdl2.py", line 42, in load
        raise Exception('SDL2: Unable to load image')

You might want to put ``pdb`` in kivy\core\image\__init__.py", line 198 and have a look which ``filename`` fails to load.

**Comment by akshayaurora** [comment]
@matham I am ok with closing this, least this can act as reminder if this issue comes up again for someone else. 

Issue seems to be cause zlib is not being detected in path, however it is included in the wheels provided with kivy. Something in the user's env is preventing these libs to be picked up.

**Comment by abhigenie92** [comment]
Hey! I am facing the exactly same issue. 
```
$ python __main__.py
Purge log fired. Analysing...
Purge 69 log files
Purge finished!
[INFO              ] [Logger      ] Record log in c:/Users/sony\.kivy\logs\kivy_16-04-15_34.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO              ] [Text        ] Provider: pil(['text_sdl2'] ignored)
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <4.0.0 - Build 10.18.10.4276>
[INFO              ] [GL          ] OpenGL vendor <Intel>
[INFO              ] [GL          ] OpenGL renderer <Intel(R) HD Graphics 4000>
[INFO              ] [GL          ] OpenGL parsed version: 4, 0
[INFO              ] [GL          ] Shading version <4.00 - Build 10.18.10.4276>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <16>
[WARNING           ] [Image       ] Unable to load image <c:\Python27\lib\site-packages\kivy\data\glsl\default.png>
[CRITICAL          ] [Window      ] Unable to find any valuable Window provider at all!
sdl2 - Exception: SDL2: Unable to load image
  File "c:\Python27\lib\site-packages\kivy\core\__init__.py", line 67, in core_select_lib
    cls = cls()
  File "c:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 138, in __init__
    super(WindowSDL, self).__init__()
  File "c:\Python27\lib\site-packages\kivy\core\window\__init__.py", line 722, in __init__
    self.create_window()
  File "c:\Python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 255, in create_window
    super(WindowSDL, self).create_window()
  File "c:\Python27\lib\site-packages\kivy\core\window\__init__.py", line 897, in create_window
    self.render_context = RenderContext()
  File "kivy\graphics\instructions.pyx", line 756, in kivy.graphics.instructions.RenderContext.__init__ (kivy\graphics\instructions.c:10729)
  File "c:\Python27\lib\site-packages\kivy\core\image\__init__.py", line 512, in __init__
    self.filename = arg
  File "c:\Python27\lib\site-packages\kivy\core\image\__init__.py", line 700, in _set_filename
    mipmap=self._mipmap, nocache=self._nocache)
  File "c:\Python27\lib\site-packages\kivy\core\image\__init__.py", line 430, in load
    im = loader(filename, **kwargs)
  File "c:\Python27\lib\site-packages\kivy\core\image\__init__.py", line 198, in __init__
    self._data = self.load(filename)
  File "c:\Python27\lib\site-packages\kivy\core\image\img_sdl2.py", line 42, in load
    raise Exception('SDL2: Unable to load image')

[CRITICAL          ] [App         ] Unable to get a Window, abort.

```

I tried:

> 
> python -m pip uninstall pillow
> python -m pip install --use-wheel pillow

Still doesn't work.

**Comment by sarmamen** [comment]
do the regular instalation. but when you will writte your program, append
the first two lines to your program. For example:

# you need this two lines:
import os
os.environ['KIVY_IMAGE'] = 'pil,sdl2'

#kivy program
from kivy.app import App
from kivy.uix.button import Button

class TestApp(App):
    def build(self):
        return Button(text='Hello World')

TestApp().run()

**Comment by abhigenie92** [comment]
@sarmamen Thanks for the reply! After doing that it works but I have the following issue:
```
Exception Exception: Exception('tostring() has been removed. Please call tobytes() instead.',) in 'kivy.graphics.instructions.RenderContext.set_texture' ignored
 Exception Exception: Exception('tostring() has been removed. Please call tobytes() instead.',) in 'kivy.graphics.instructions.RenderContext.set_texture' ignored
 Exception Exception: Exception('tostring() has been removed. Please call tobytes() instead.',) in 'kivy.graphics.instructions.RenderContext.set_texture' ignored
 Exception Exception: Exception('tostring() has been removed. Please call tobytes() instead.',) in 'kivy.graphics.instructions.RenderContext.set_texture' ignored
```

The buttons and labels are displayed incorrectly as shown in the image below.
![capture](https://cloud.githubusercontent.com/assets/12474640/14566460/51fcb4c4-034d-11e6-8a96-5b84a62e34c3.PNG)

**Comment by sarmamen** [comment]
i rly dont know what the problem is :/ i have never had such a problem. My
sugestion is that you go to the irc channel of kivy and ask there. I hope
someone will help you:

https://webchat.freenode.net/
Nickname: sample_nick
Channels: #kivy

**Comment by kived** [comment]
If you're getting this error, then you're not running the 1.9.1 release. Either you're on a pre-release dev version, or you have something wrong with your installation.

https://github.com/kivy/kivy/commit/ff178501c2744613bdb1327e927f9f759f630bc8

**Comment by abhigenie92** [comment]
@kived I am running the latest one. 
```
Abhishek@ABHISHEK ~/Dropbox/notepad_app/2_Paint (master)
$ python -m pip install kivy --upgrade
Requirement already up-to-date: kivy in c:\python27\lib\site-packages
Requirement already up-to-date: Kivy-Garden>=0.1.4 in c:\python27\lib\site-packages (from kivy)
Collecting requests (from Kivy-Garden>=0.1.4->kivy)
  Using cached requests-2.9.1-py2.py3-none-any.whl
Installing collected packages: requests
  Found existing installation: requests 2.7.0
    Uninstalling requests-2.7.0:
      Successfully uninstalled requests-2.7.0
Successfully installed requests-2.9.1

Abhishek@ABHISHEK ~/Dropbox/notepad_app/2_Paint (master)
$ python -m pip freeze | grep kivy
kivy.deps.glew==0.1.4
kivy.deps.gstreamer==0.1.5
kivy.deps.sdl2==0.1.12```

**Comment by kived** [comment]
Version 1.9.1 calls `tobytes()`, not `tostring()`. I double-checked the wheel on PyPI and it is correct. This likely circles back to the original problem, which is that something in your environment or system is incorrect.

**Comment by dessant** [comment]
@kived, this was fixed after 1.9.1 in the text provider: https://github.com/kivy/kivy/commit/83a9528acc0f369c364a02812e49f47792152fd3.

@abhigenie92, you could try updating to the dev version, the docs have instructions.
Even if pillow will work, the text doesn't look too good with it, your end goal would be to find out why does the sdl2 text provider fail to load.

**Comment by abhigenie92** [comment]
@dessant thanks! 
Are to you referring to https://kivy.org/docs/installation/installation-windows.html#installation
```
Abhishek@ABHISHEK ~/Dropbox/notepad_app/2_Paint (master)
$ python -m pip install --upgrade pip wheel setuptools
Requirement already up-to-date: pip in c:\python27\lib\site-packages
Requirement already up-to-date: wheel in c:\python27\lib\site-packages
Requirement already up-to-date: setuptools in c:\python27\lib\site-packages

Abhishek@ABHISHEK ~/Dropbox/notepad_app/2_Paint (master)
$ python -m pip install docutils pygments pypiwin32 kivy.deps.sdl2 kivy.deps.glew kivy.deps.gstreamer --extra-index-url htt
ps://kivy.org/downloads/packages/simple/ --upgrade
Requirement already up-to-date: docutils in c:\python27\lib\site-packages
Requirement already up-to-date: pygments in c:\python27\lib\site-packages
Requirement already up-to-date: pypiwin32 in c:\python27\lib\site-packages
Requirement already up-to-date: kivy.deps.sdl2 in c:\python27\lib\site-packages
Requirement already up-to-date: kivy.deps.glew in c:\python27\lib\site-packages
Requirement already up-to-date: kivy.deps.gstreamer in c:\python27\lib\site-packages

Abhishek@ABHISHEK ~/Dropbox/notepad_app/2_Paint (master)
$ python -m pip install kivy --upgrade
Requirement already up-to-date: kivy in c:\python27\lib\site-packages
Requirement already up-to-date: Kivy-Garden>=0.1.4 in c:\python27\lib\site-packages (from kivy)
Requirement already up-to-date: requests in c:\python27\lib\site-packages (from Kivy-Garden>=0.1.4->kivy)
```
This still doesn't fix. What do you guys @kived @dessant suggest?

**Comment by dessant** [comment]
Your link is for kivy stable, for the dev version follow https://kivy.org/docs/installation/installation-windows.html#nightly-wheel-installation.

**Comment by dessant** [comment]
@matham, the last nightly wheel on drive seems to be from march 31.

**Comment by matham** [comment]
It's an April fools joke?

**Comment by matham** [comment]
The joke is that it is uploaded, but you cannot find it (in case you didn't get it ;) ). Just search for `Kivy-1.9.2.dev0_14042016_git_af57cd3-cp34_14042016_git_af57cd3-cp34m-win_amd64`.

**Comment by abhigenie92** [comment]
Following https://kivy.org/docs/installation/installation-windows.html#nightly-wheel-installation.
```
Abhishek@ABHISHEK /C/Users/sony/python_packages (master)
$ python -m pip install "Kivy-1.9.2.dev0-cp27m-win32.whl"
Kivy-1.9.2.dev0-cp27m-win32.whl is not a valid wheel filename.
```
Pip works:
```
>>> import pip; print(pip.pep425tags.get_supported())
[('cp27', 'cp27m', 'win32'), ('cp27', 'none', 'win32'), ('py2', 'none', 'win32'), ('cp27', 'none', 'any'), ('cp2', 'none', 'any'), ('py27', 'none', 'any'), ('py2', 'none', 'any'), ('py26', 'none', 'any'), ('py25', 'none', 'any'), ('py24', 'none', 'any'), ('py23', 'none', 'any'), ('py22', 'none', 'any'), ('py21', 'none', 'any'), ('py20', 'none', 'any')]
>>>
```
Should I not rename?

**Comment by dessant** [comment]
@matham, i was not able to sort the list in any way, and the end of it seemed like it is in chronological order. :yum:
We could link to the latest build somehow from the docs instead, while still mentioning the scary folder:
https://drive.google.com/folderview?id=0B1_HB9J8mZepOV81UHpDbmg5SWM&usp=sharing#grid

**Comment by KeyWeeUsr** [comment]
@dessant You can use simple regex `"(Kivy-\d\.\d\.\d)(\.\w{4}_`ddmmyyyy`_git\_?\w{7}-`cp34 or cp27`)(-none|_\d{8}_git_\w{7}-`cp34m or cp27m`)(-`win_amd64 or win32`.whl)"` at drive [list view](https://drive.google.com/folderview?id=0B1_HB9J8mZepOV81UHpDbmg5SWM&usp=sharing#list), where ddmmyyyy is the date of "yesterday" to get each group of the wheel name and pass to user the correct name directly so that a user only downloads the nightly build with a correct name. I use this for [KivyInstaller](https://github.com/KeyWeeUsr/KivyInstaller)

To get it done either use standalone [javascript](http://stackoverflow.com/a/4229141/5994041) outside of the docs(which would be easier to change when wheel name changes for whatever reason), or php/jQuery, or well.. directly in python, but I presume that'd require building docs everytime nightly wheel is built if you don't use python on your server.

**Comment by Buchx** [comment]
I am getting very same issue as OP.
First i tried the following standard - gave me this error:
`Purge log fired. Analysing...
Purge 12 log files
[INFO   ] [Logger      ] Record log in C:\Users\Buch\.kivy\logs\kivy_17-12-15_98.txt
Purge finished!
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif (img_sdl2, img_pil, img_ffpyplayer ignored)
[CRITICAL] [Text        ] Unable to find any valuable Text provider.
sdl2 - ImportError: DLL load failed: Det angivne modul blev ikke fundet.
  File "C:\Users\Buch\.virtualenvs\KEABAR\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\Buch\.virtualenvs\KEABAR\lib\site-packages\kivy\core\text\text_sdl2.py", line 12, in <module>
    from kivy.core.text._text_sdl2 import (_SurfaceContainer, _get_extents,

pil - ModuleNotFoundError: No module named 'PIL'
  File "C:\Users\Buch\.virtualenvs\KEABAR\lib\site-packages\kivy\core\__init__.py", line 59, in core_select_lib
    fromlist=[modulename], level=0)
  File "C:\Users\Buch\.virtualenvs\KEABAR\lib\site-packages\kivy\core\text\text_pil.py", line 7, in <module>
    from PIL import Image, ImageFont, ImageDraw

[CRITICAL] [App         ] Unable to get a Text provider, abort.
`

Tried adding: `import os
os.environ['KIVY_IMAGE'] = 'pil,sdl2'`

Just gives mes this and now GUI :)
`[INFO   ] [Logger      ] Record log in C:\Users\Buch\.kivy\logs\kivy_17-12-15_99.txt
[INFO   ] [Kivy        ] v1.10.0
[INFO   ] [Python      ] v3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers:  (img_tex, img_dds, img_ffpyplayer, img_gif, img_pil, img_sdl2 ignored)
[CRITICAL] [App         ] Unable to get any Image provider, abort.`

Kind regards

**Comment by Jrius4** [comment]
Am also facing this problem please i will be grateful cause am new to kivy 

C:\Users\Kaxibwe>python c:\python27\share\kivy-examples\demo\showcase\main.py
[INFO   ] [Logger      ] Record log in C:\Users\Kaxibwe\.kivy\logs\kivy_17-12-23
_1.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-0456eff, 20171125
[INFO   ] [Python      ] v2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MS
C v.1500 32 bit (Intel)]
 Traceback (most recent call last):
   File "c:\python27\share\kivy-examples\demo\showcase\main.py", line 29, in <mo
dule>
     from kivy.app import App
   File "C:\Python27\kivy\app.py", line 319, in <module>
     from kivy.base import runTouchApp, stopTouchApp
   File "C:\Python27\kivy\base.py", line 26, in <module>
     from kivy.clock import Clock
   File "C:\Python27\kivy\clock.py", line 362, in <module>
     from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
 ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by Jrius4** [comment]
am failing to debug this..

c:\Python27>python c:\python27\share\kivy-examples\camera\main.py
[INFO   ] [Logger      ] Record log in C:\Users\Kaxibwe\.kivy\logs\kivy_17-12-2
_4.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-0456eff, 20171125
[INFO   ] [Python      ] v2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [M
C v.1500 32 bit (Intel)]
 Traceback (most recent call last):
   File "c:\python27\share\kivy-examples\camera\main.py", line 17, in <module>
     from kivy.app import App
   File "c:\Python27\kivy\app.py", line 319, in <module>
     from kivy.base import runTouchApp, stopTouchApp
   File "c:\Python27\kivy\base.py", line 26, in <module>
     from kivy.clock import Clock
   File "c:\Python27\kivy\clock.py", line 362, in <module>
     from kivy._clock import CyClockBase, ClockEvent, FreeClockEvent, \
 ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by pkemarco** [comment]
I have you install all dependencies ? Install All is needed. See the kivy
website

2017-12-23 7:08 GMT+01:00 Jrius Kaxibwe <notifications@github.com>:

**Comment by alonoz** [comment]
Same problem, latest git version

**Comment by xyyxhcj** [comment]
Same issue, version 2.1.0
