### ISSUE TITLE
Error creating panel with the json file in Kivy

### ISSUE THREAD

**Issue by HeaTTheatR** [kivy/kivy#4386]
Tell me why the code that works in Python 27 does not work in the third version, though like all right?

**theme.json**

    [
    {{"type": "title",
      "title": "{a}" }},

    {{"type": "options",
      "title": "{b}",
      "desc": "{c}",
      "section": "Theme",
      "key": "theme",
      "options": ["{d}"] }},

    {{"type": "bool",
      "title": "{e}",
      "desc":  "{f}",
      "section": "Theme",
      "key": "edit_theme",
      "true": "auto" }},

    {{"type": "bool",
      "title": "{g}",
      "desc":  "{h}",
      "section": "Theme",
      "key": "create_theme",
      "true": "auto" }}
    ]

**test.py**

    #! /usr/bin/python3.4

    import traceback

    try:
        import kivy
        kivy.require('1.9.2')

        from kivy.app import App
        from kivy.config import ConfigParser
        from kivy.uix.button import Button
    except Exception:
        raise Exception(traceback.format_exc())

    class Program(App):

        def __init__(self, **kvargs):
            super().__init__()

        def build_config(self, config):
            config.adddefaultsection("Theme")
            config.setdefault("Theme", "theme", "blue_orange")
            config.setdefault("Theme", "edit_theme", "0")
            config.setdefault("Theme", "create_theme", "0")

        def build_settings(self, settings):
            theme_settings = open('theme.json').read()
            theme_data = theme_settings.format(
                a='1', b='2', c='3', d='4', e='5', f='6', g='7', h='8')
            settings.add_json_panel('Theme', self.config, data=theme_data)
        
        def build(self):
            self.config = ConfigParser()
            self.config.read('program.ini')
            return Button(text='Press', on_press=self.open_settings)

    Program().run()

Tell me where the error?

**Text error:**
    
    Traceback (most recent call last):
       File "test.py", line 39, in <module>
         Program().run()
       File "/usr/local/lib/python3.4/dist-packages/kivy/app.py", line 828, in run
         runTouchApp()
       File "/usr/local/lib/python3.4/dist-packages/kivy/base.py", line 487, in runTouchApp
         EventLoop.window.mainloop()
       File "/usr/local/lib/python3.4/dist-packages/kivy/core/window/window_pygame.py", line 403, in mainloop
         self._mainloop()
       File "/usr/local/lib/python3.4/dist-packages/kivy/core/window/window_pygame.py", line 290, in _mainloop
         EventLoop.idle()
       File "/usr/local/lib/python3.4/dist-packages/kivy/base.py", line 330, in idle
         self.dispatch_input()
       File "/usr/local/lib/python3.4/dist-packages/kivy/base.py", line 315, in dispatch_input
         post_dispatch_input(*pop(0))
       File "/usr/local/lib/python3.4/dist-packages/kivy/base.py", line 221, in post_dispatch_input
         listener.dispatch('on_motion', etype, me)
       File "_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7173)
       File "/usr/local/lib/python3.4/dist-packages/kivy/core/window/__init__.py", line 1034, in on_motion
         self.dispatch('on_touch_down', me)
       File "_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7173)
     File "/usr/local/lib/python3.4/dist-packages/kivy/core/window/__init__.py", line 1050, in on_touch_down
         if w.dispatch('on_touch_down', touch):
       File "_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7173)
       File "/usr/local/lib/python3.4/dist-packages/kivy/uix/behaviors/button.py", line 159, in on_touch_down
         self.dispatch('on_press')
       File "_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy/_event.c:7132)
       File "_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy/_event.c:12357)
       File "_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (kivy/_event.c:11955)
       File "/usr/local/lib/python3.4/dist-packages/kivy/app.py", line 916, in open_settings
         self._app_settings = self.create_settings()
       File "/usr/local/lib/python3.4/dist-packages/kivy/app.py", line 985, in create_settings
         self.build_settings(s)
       File "test.py", line 31, in build_settings
         settings.add_json_panel('Theme', self.config, data=theme_data)
       File "/usr/local/lib/python3.4/dist-packages/kivy/uix/settings.py", line 950, in add_json_panel
         panel = self.create_json_panel(title, config, filename, data)
       File "/usr/local/lib/python3.4/dist-packages/kivy/uix/settings.py", line 990, in create_json_panel
         instance = cls(panel=panel, **str_settings)
       File "/usr/local/lib/python3.4/dist-packages/kivy/uix/settings.py", line 289, in __init__
         super(SettingItem, self).__init__(**kwargs)
       File "/usr/local/lib/python3.4/dist-packages/kivy/uix/floatlayout.py", line 65, in __init__
         super(FloatLayout, self).__init__(**kwargs)
       File "/usr/local/lib/python3.4/dist-packages/kivy/uix/layout.py", line 72, in __init__
         super(Layout, self).__init__(**kwargs)
       File "/usr/local/lib/python3.4/dist-packages/kivy/uix/widget.py", line 312, in __init__
         super(Widget, self).__init__(**kwargs)
       File "_event.pyx", line 254, in kivy._event.EventDispatcher.__init__ (kivy/_event.c:4673)
     TypeError: object.__init__() takes no parameters

I have a big list of settings. By process of elimination, I found that the problem is in the above json file.

**Comment by markmelvin** [comment]
This seems to be a bug in Kivy related to #3699.  Following the settings panel video tutorial using Python 3.4 also crashes in a similar manner for me:

 Traceback (most recent call last):
   File "main.py", line 191, in <module>
     MyDemo().run()
   File "C:\Python34\lib\site-packages\kivy\app.py", line 828, in run
     runTouchApp()
   File "C:\Python34\lib\site-packages\kivy\base.py", line 487, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
     self._mainloop()
   File "C:\Python34\lib\site-packages\kivy\core\window\window_sdl2.py", line 556, in _mainloop
     self.modifiers)
   File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7654)
   File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
   File "kivy\_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (kivy\_event.c:13023)
   File "C:\Python34\lib\site-packages\kivy\app.py", line 1033, in _on_keyboard_settings
     if not self.open_settings():
   File "C:\Python34\lib\site-packages\kivy\app.py", line 916, in open_settings
     self._app_settings = self.create_settings()
   File "C:\Python34\lib\site-packages\kivy\app.py", line 985, in create_settings
     self.build_settings(s)
   File "main.py", line 179, in build_settings
     settings.add_json_panel('Program Options', self.config, data=settings_json)

   File "C:\Python34\lib\site-packages\kivy\uix\settings.py", line 951, in add_json_panel
     panel = self.create_json_panel(title, config, filename, data)
   File "C:\Python34\lib\site-packages\kivy\uix\settings.py", line 991, in create_json_panel
     instance = cls(panel=panel, **str_settings)
   File "C:\Python34\lib\site-packages\kivy\uix\settings.py", line 290, in __init__
     super(SettingItem, self).__init__(**kwargs)
   File "C:\Python34\lib\site-packages\kivy\uix\floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "C:\Python34\lib\site-packages\kivy\uix\layout.py", line 72, in __init__

     super(Layout, self).__init__(**kwargs)
   File "C:\Python34\lib\site-packages\kivy\uix\widget.py", line 312, in __init__
     super(Widget, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 254, in kivy._event.EventDispatcher.__init__ (kivy\_event.c:4895)
 TypeError: object.__init__() takes no parameters

**Comment by dessant** [comment]
Fixed in https://github.com/kivy/kivy/pull/3699.

**Comment by markmelvin** [comment]
It's not fixed.  I am using Kivy 1.9.1 with this change merged and it still fails.

**Comment by dessant** [comment]
Ah sorry, I thought it was the exact same bug.

**Comment by markmelvin** [comment]
I think #3579 is a duplicate of this and is also not fixed.  However, something is fishy because I can run the Kivy example just fine.  I'm digging further.

**Comment by markmelvin** [comment]
Turns out I had the 'desc' item in my json as 'description'.  This causes that weird failure.  So, the original poster should check that their end json is proper.  I see your boolean options have "true" in them.  Not sur that is valid.

**Comment by HeaTTheatR** [comment]
It works like this (without arguments [b]"true": "auto"[/b])

[b]theme.json[/b]

    [
    {{"type": "title",
      "title": "{a}" }},

    {{"type": "options",
      "title": "{b}",
      "desc": "{c}",
      "section": "Theme",
      "key": "theme",
      "options": ["{d}"] }},

    {{"type": "bool",
      "title": "{e}",
      "desc":  "{f}",
      "section": "Theme",
      "key": "edit_theme" }},

    {{"type": "bool",
      "title": "{g}",
      "desc":  "{h}",
      "section": "Theme",
      "key": "create_theme"}}
]

**Comment by Jowls1** [comment]
I'm still getting an error with Python 3.5 on Raspbian Stretch on a Praspberry Pi Model 3 B+.  Kivy version is v2.0.0.dev0, git-fd7e81e.  

When I call add_json_panel(), I get the following error:

```
03-Dec-19 11:43:18.941 [GUI] - Error: Traceback (most recent call last):
  File "/opt/24acoustics/ro/modules/kivyapp.py", line 1623, in button_pressed
    self.open_settings()
  File "/usr/local/lib/python3.5/dist-packages/kivy/app.py", line 1057, in open_settings
    self._app_settings = self.create_settings()
  File "/usr/local/lib/python3.5/dist-packages/kivy/app.py", line 1126, in create_settings
    self.build_settings(s)
  File "/opt/24acoustics/ro/modules/kivyapp.py", line 978, in build_settings
    data=self.remove_bad_keys_from_json_string(self.visible_settings[0]))
  File "/usr/local/lib/python3.5/dist-packages/kivy/uix/settings.py", line 977, in add_json_panel
    panel = self.create_json_panel(title, config, filename, data)
  File "/usr/local/lib/python3.5/dist-packages/kivy/uix/settings.py", line 1017, in create_json_panel
    instance = cls(panel=panel, **str_settings)
  File "/usr/local/lib/python3.5/dist-packages/kivy/uix/label.py", line 318, in __init__
    super(Label, self).__init__(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/kivy/uix/widget.py", line 350, in __init__
    super(Widget, self).__init__(**kwargs)
  File "kivy/_event.pyx", line 245, in kivy._event.EventDispatcher.__init__
TypeError: object.__init__() takes no parameters
```

The solution I've found is to replace part of the create_json_panel() function in /usr/local/lib/python3.5/dist-packages/kivy/uix/settings.py:

```
if ttype == 'title':
    instance = cls(panel=panel)
else:
    instance = cls(panel=panel, **str_settings)
```

That's because it only complained with the 'title' items.  I never had this problem with Python 2.  I don't know if this is a genuine bug, but this might help someone else experiencing the problem.
