### ISSUE TITLE
[Raspberry Pi 3] - ScreenManager and the 12 transitions

### ISSUE THREAD

**Issue by biank88** [kivy/kivy#4662]
**Platform**:
- Kivy: v1.9.2-dev0@master
- Raspberry 3
- Official 7" RPI touch screen

**App**:
/kivy/examples/demo/showcase/main.py

**Short description**:
In the showcase demo, testing "Screenmanager" with "Fade Transition" and "Wipe Transition" produces some weird errors.
## **Fade Transition** error:

As you can see from the video below, for every "FadeTransition" transition, the error `glGetError 0x502` is thrown in the shell... then, after 12 transitions, a black screen suddenly appears and the folowing warning is shown: `[WARNING] stderr: Exception ignored in: 'kivy.graphics.fbo.Fbo.raise_exception'
[WARNING] stderr: Exception: FBO Initialization failed: Incomplete attachment (36054)`

**Kivy log**: [kivy_16-10-07_3--fade-transition-error.txt](https://github.com/kivy/kivy/files/516074/kivy_16-10-07_3--fade-transition-error.txt)
**Video**: https://www.youtube.com/watch?v=lu4Rh55EK1E
**Screenshot**: 
![kivy_16-10-07_3--fade-transition-error](https://cloud.githubusercontent.com/assets/1591429/19190019/5316f4dc-8c9b-11e6-9a64-121799d7350c.png)
## **Wipe Transition** error:

Similarly, for every "WipeTransition" transition, the error `glGetError 0x502` is thrown in the shell... then, after 12 transitions, a black screen suddenly appears and the folowing warning is shown: `[WARNING] stderr: Exception ignored in: 'kivy.graphics.fbo.Fbo.raise_exception' [WARNING] stderr: Exception: FBO Initialization failed: Incomplete attachment (36054)`

**Kivy log**:[kivy_16-10-07_8--wipe-transition-error.txt](https://github.com/kivy/kivy/files/516193/kivy_16-10-07_8--wipe-transition-error.txt)
**Video**:https://www.youtube.com/watch?v=GWGgR7etw5w
**Screenshot**:

**Comment by rnixx** [comment]
might be related to #4542

**Comment by cangelis** [comment]
Try increasing the GPU memory. You can edit `/boot/config.txt` and append `gpu_mem=256`. More information [here](http://raspberrypi.stackexchange.com/questions/673/what-is-the-optimum-split-of-main-versus-gpu-memory)

**Comment by jmptbl** [comment]
I'm experiencing this too, with Kivy 1.9.1. Increasing gpu_mem from 128 to 512 makes no difference.

I've noticed that it doesn't occur with the Swap and Slide transitions.

**Comment by jmptbl** [comment]
FWIW I stumbled upon these OpenGL error codes:

https://www.khronos.org/opengl/wiki/OpenGL_Error

Apparently it's 0x0505 that means "out of memory", while 0x0502 means "invalid operation".

**Comment by frankgould** [comment]
Has there been any solutions to this glGetError 0x502 and crashing problem? I'm having the same issue but can't find a solution. I tried the 512M gpu_mem config but there was no difference, still error and crash.

**Comment by frankgould** [comment]
I was experiencing this same shader link problem and with the help of others was able to determine a memory leak in one of the kivy modules that has been fixed. If you can pull the latest kivy master files, you can test to see if this latest version solves this issue. For more information about a repetitive glGetError 0x502 messages, reference #5581. This revision should also fix #4542.

**Comment by tito** [comment]
Fixed by #5664 - Please reopen if it is not the case.

**Comment by pro90** [comment]
I still get this issue on a RPi 3 with Kivy installed on a vanilla Raspbian stretch image. I followed the installation instructions described on the Kivy homepage for the raspberry pi. I am using Python 3.5.3 and compiled kivy from master branch (Kivy: v1.10.1.dev0, git-2efa46a, 20180516). This is the log I get when running the kivy showcase demo, switching between two screens, exactly as bionid does in the youtube video:

[kivy_18-05-17_1.txt](https://github.com/kivy/kivy/files/2012878/kivy_18-05-17_1.txt)

This is with Legacy OpenGL driver activated with 256MB memory split. I also get glGetError x0505 and x0502 not shown in the log. I get the same errors when activating FullKMS OpenGL driver.

**Comment by kuzeyron** [comment]
@pro90 On my Pi2 I've set in `/boot/config.txt` -> `gpu_mem=190`
Hope it helps.

**Comment by pro90** [comment]
What screen resolution do you use? Can you maybe post a step by step guide for your working kivy setup? I followed the steps exactly as described in this Kivy manual [link](https://kivy.org/docs/installation/installation-rpi.html), starting with the most recent raspbian distro i found on raspberrypi.org. I only changed the python packages to python3 packages and changed gpu_memory to 256MB via raspi-config

**Comment by kuzeyron** [comment]
@pro90 are you on HDMI or official screen?
You could try go through their [Config Tutorial](https://www.raspberrypi.org/documentation/configuration/config-txt/video.md) for the HDMI/Display.

What I've learned with Raspberry Pi is, you should put everything in the /boot/config.txt instead of messing around with other things.

If you have another Micro-SD card. You could try running [KivyPie](http://kivypie.mitako.eu), to see if it works there. I usually go with KivyPie instead of using Raspbian. It's easier to setup with KivyPie.

**Comment by frankgould** [comment]
Since this issue is still being discussed, I would like to say that it should be opened again because after further testing the fix mentioned above, I got the same glGetErrors. The reason I found it to work after it was fixed was because my test code was running without an HDMI monitor attached. Once I ran my test code with the monitor, the same problem returned and I gave up. If this can be fixed to support this configuration change (HDMI monitor), I will be glad to continue testing with kivy. Otherwise, I'm currently migrating my code to pi3d, which also has GPU memory problems but doesn't crash my app like it does with kivy screenmanager.

**Comment by kuzeyron** [comment]
All of you who have this problem.
Write down in details how you installed Kivy (step by step..).
I'm going to run some tests to see if I get the same problem as you.

**Comment by frankgould** [comment]
Here is my Linux distribution version info:
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"

script used to install kivy:
```
cd /home/pi
sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev pkg-config libgl1-mesa-dev libgles2-mesa-dev python-setuptools libgstreamer1.0-dev git-core gstreamer1.0-plugins-{bad,base,good,ugly} gstreamer1.0-{omx,alsa} python-dev libmtdev-dev xclip xsel
git clone https://github.com/kivy/kivy
cd /home/pi/kivy
make
echo "export PYTHONPATH=$(pwd):\$PYTHONPATH" >> ~/.profile
source ~/.profile

```

**Comment by tshirtman** [comment]
@kuzeyron i was doing some tests myself
- got an rpi3B
- downloaded latest kivypie and put it on an sdcard
- apt-get update && apt-get dist-upgrade
- rpi-update
- resized fs to full size
- cloned kivy and pip installed Cython==0.26 in a virtualenv then python setup.py install (the kivypie doc says to unmount /tmp so i did)
- edited ~/.kivy/config.ini to commend the hid device and touchring module (replaced by cursor module) (needed to be able to select dropdowns with mouse)
- edited /boot/config.txt and raised gpu_mem to 512 (but did *not* reboot yet)
- light edits to showcase to avoid issues with KivyLexer (since i build without deps for that)
- ran python example/demo/showcase/main.py
- selected she screenmanager one, and played the wipe transition a few time, error 0x502 right away, and after a few time, the transition is black. no more shader effect
- rebooted to apply the gpu mem config
- loaded virtualenv and ran again, 0x502 errors are still there, but no more black transition, i assume it could happen after a lot more usage though. FadeTransition also produces the error.
- edit config.txt again to go back to 128 and reboot.
- after playing the example in the same condition i get the 0x502 errors again, and
```
 Exception: FBO Initialization failed: Incomplete attachment (36054)
 Exception Exception: Exception('FBO Initialization failed: Incomplete attachment (36054)',) in 'kivy.graphics.fbo.Fbo.raise_exception' ignored
glGetError 0x505
```
when the transition doesn't work (black), which is after as few as 2 transitions of wipetransition.

**Comment by bionoid** [comment]
OpenGL docs have a pretty detailed list of possible reasons:

**GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT** ([source](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glCheckFramebufferStatus.xml))

> Not all framebuffer attachment points are framebuffer attachment complete. This means that at least one attachment point with a renderbuffer or texture attached has **(1)** its attached object no longer in existence or **(2)** has an attached image with a width or height of zero, or **(3)** the color attachment point has a non-color-renderable image attached, or **(4)** the depth attachment point has a non-depth-renderable image attached, or **(5)** the stencil attachment point has a non-stencil-renderable image attached.

> Color-renderable formats include GL_RGBA4, GL_RGB5_A1, and GL_RGB565. GL_DEPTH_COMPONENT16 is the only depth-renderable format. GL_STENCIL_INDEX8 is the only stencil-renderable format.

Hopefully some of these can be ruled out relatively easily? ScreenManager uses an FBO with stencilbuffer, could that be related to (5)?

Can someone gist a log with `KIVY_GL_DEBUG=1`? Maybe it contains clues. Another thought is to run [tito's apitrace script](https://gist.github.com/tito/1174b86ce126fd1ac11afbc77750d9ac) from the last time around, in case nobody tried that yet

**Comment by bionoid** [comment]
#4212 reports incomplete attachment on RPi2 when FBO is not NPOT! Could that be the case here as well?

**Comment by kuzeyron** [comment]
How I did install Kivy in Raspbian

`Raspbian: v8, Python: 2.7.9 and 3.6.5`


`sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev    pkg-config libgl1-mesa-dev libgles2-mesa-dev    python-setuptools libgstreamer1.0-dev git-core    gstreamer1.0-plugins-{bad,base,good,ugly}    gstreamer1.0-{omx,alsa} python-dev libmtdev-dev    xclip xsel`  
`sudo pip install cython==0.25.2`  

`pip install git+https://github.com/kivy/kivy.git@master`
And that's it. Nothing else to do.

And my `/boot/config.txt`:
```lcd_rotate=2
disable_splash=1
gpu_mem=190
arm_freq=1050
gpu_freq=470
force_turbo=1
over_voltage=6
temp_limit=80
gpu_mem_256=142
gpu_mem_512=398
dtparam=audio=on
coherent_pool=6M smcsc95xx.turbo_mode=N
start_x=0
core_freq=500
sdram_freq=500
```

A little bonus to add: `pip install rpi_backlight`

**Comment by pro90** [comment]
@kuzeyron Which screen are you using at which resolution? As @frankgould pointed out, this bug seems to be output or resolution dependent.

**Comment by kuzeyron** [comment]
@pro90 I'm using the Raspberry Pi's official 7" screen.

**Comment by pro90** [comment]
can you maybe try a LCD display via HDMI with a resolution of at least 1280x1024?

**Comment by pro90** [comment]
my installation routine: started out with a vanilla "Raspbian Stretch with Desktop" image, April 2018 version (4.14-34 kernel) 

`sudo apt-get update`
`sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
   pkg-config libgl1-mesa-dev libgles2-mesa-dev \
   python3-setuptools libgstreamer1.0-dev git-core \
   gstreamer1.0-plugins-{bad,base,good,ugly} \
   gstreamer1.0-{omx,alsa} python3-dev libmtdev-dev \
   xclip xsel`
`sudo pip3 install -U Cython==0.28.2`
`sudo pip3 install git+https://github.com/kivy/kivy.git@master`

Afterwards I tested the my own application as well as kivy demo applications with different combinations of memory split (128 / 256 MB) and OpenGL drivers (Legacy or Full KMS OGL desktop driver).

**Comment by kuzeyron** [comment]
Okay, tested with the release `2018-04-18` of Raspbian and here is the log output:
```
pi@raspberrypi:~/test $ python main.py 
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_18-05-23_2.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-6c7fce6, 20180523
[INFO   ] [Python      ] v2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
Unable to init server: Could not connect: Connection refused

(main.py:7264): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Unable to init server: Could not connect: Connection refused

(main.py:7264): Gtk-CRITICAL **: gtk_clipboard_get_for_display: assertion 'display != NULL' failed
[INFO   ] [Clipboard   ] Provider: gtk3(['clipboard_dbusklipper'] ignored)
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO   ] [Cutbuffer   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [OSC         ] using <multiprocessing> for socket
Unable to connect to X server
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [HIDInput    ] Read event from </dev/input/event1>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [HIDMotionEvent] using <Microsoft Comfort Curve Keyboard 2000>
[INFO   ] [HIDMotionEvent] using <Microsoft Comfort Curve Keyboard 2000>

```
And to mention, I ran this from the desktop itself rather fullscreen.

**Comment by pro90** [comment]
which application do you use for testing? can you maybe share the code of your test app? can you also test it with python3?

**Comment by kuzeyron** [comment]
@pro90 First program I tried was just a simple RecycleView that @tshirtman helped me with.
My 2nd attempt to make it harder for the Pi I used this code: [main.py](https://gist.github.com/kuzeyron/b43c72f59fa1dec22919e3a02e353175)

The log:
```
pi@raspberrypi:~/test $ python main.py 
[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_18-05-23_4.txt
[INFO   ] [Kivy        ] v1.10.1.dev0, git-6c7fce6, 20180523
[INFO   ] [Python      ] v2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516]
[INFO   ] [Factory     ] 194 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil, img_gif (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <OpenGL ES 2.0>
[INFO   ] [GL          ] OpenGL vendor <Broadcom>
[INFO   ] [GL          ] OpenGL renderer <VideoCore IV HW>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <OpenGL ES GLSL ES 1.00>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
Unable to connect to X server
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event1
[INFO   ] [HIDInput    ] Read event from </dev/input/event1>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event2
[INFO   ] [HIDInput    ] Read event from </dev/input/event2>
[INFO   ] [ProbeSysfs  ] device match: /dev/input/event0
[INFO   ] [HIDInput    ] Read event from </dev/input/event0>
[INFO   ] [Base        ] Start application main loop
[INFO   ] [HIDMotionEvent] using <Microsoft Comfort Curve Keyboard 2000>
[INFO   ] [HIDMotionEvent] using <YSTEK G Mouse>
[INFO   ] [HIDMotionEvent] using <Microsoft Comfort Curve Keyboard 2000>
[INFO   ] [Base        ] Leaving application in progress...

```
Still I haven't got the same error messages as you got. I kinda wish I had a Raspberry Pi 3/3+ for the moment.

**Comment by kuzeyron** [comment]
This should now solve the issue.

#installation process
`sudo apt-get update`
```
sudo apt-get install libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
   pkg-config libgl1-mesa-dev libgles2-mesa-dev \
   python-setuptools libgstreamer1.0-dev git-core \
   gstreamer1.0-plugins-{bad,base,good,ugly} \
   gstreamer1.0-{omx,alsa} python-dev libmtdev-dev \
   xclip xsel
```

#Using 0.25.2 because it's known to work for me
```
sudo pip install Cython==0.25.2
sudo pip install git+https://github.com/kivy/kivy.git@master
```

#No sudo!
Run: `export DISPLAY=:0.0`
You can also add it in the bottom of the `/home/pi/.bashrc` file.

The result should look like on the picture.
![alt tag](https://i.imgur.com/iydGbpr.jpg)

**Comment by Neex101** [comment]
Hi, just putting my hand up as another dead-in-the-water Pi user (3B+, Rasbian Stretch Lite, Kivy).

**Comment by frankgould** [comment]
I'm returning to this club to say I've been down a wayward path and have found a light in the tunnel. First off, Kivy screenmanager crashes due to memory leaks caused by the outdated Raspbian graphics drivers. To fix this, I migrated to Ubuntu-Mate 18.04 and am able to install opencv that I couldn't on Raspbian. Second, RPi 3B+ has compatibility problems with some Linux distributions and I've had two die on me. I now use RPi 3B models exclusively and am satisfied with the quality and reliability so far. 

I have spent 5 months migrating from Android to Mate and it has been one long arduous task. Keep trying different solutions and eventually something will work. I'm happy to share more if it helps.

**Comment by JamilHaidar** [comment]
@frankgould  Thank you for your suggestion. I flashed Ubuntu 16.04 on my Raspberry pi 3B and tried installing Kivy. Can you please send me which commands you used to install Kivy? I had used the official commands when installing on Raspbian before. Trying them on Ubuntu lead to downloading Cython but when I try to "make" kivy, it says Cython is not installed. Anyways, it'd be great if you could share the commands you used for installing kivy. Thank you! 😄

**Comment by frankgould** [comment]
After several tests across multiple linux distributions, like Ubuntu Mate 16.04 and 18.04, Gentoo, and Arch, we determined there are graphics driver problem on all of them. My buddy Kuzeyron and I have tried all possible combinations of graphics driver (legacy, KMS, and fake KMS) with these distributions. Kuzeyron has even attempted to compile the open source versions to update the drivers with newer releases but was unable to get the drivers to install correctly.

At this point, I have fallen back to my pi3d driven SlideShow app so that it can manage the GPU memory and reboot Raspbian after months running continuously. Going forward, we would like to find someone who can help us get past this graphics driver memory leak in Raspbian so that the Kivy screenmanager works without crashing the Raspberry Pi.

Is there anyone who can help us with this anomaly? If so, you can usually find one of us on the Kivy channel on Discord.

**Comment by OutsourcedGuru** [comment]
I'm weighing in here as well. My OctoPrint plugin uses Kivy and includes a `screenmanager` object within Python code on a Raspberry Pi 3B. It has a slow memory leak which eventually fills available RAM, then swap space and then crashes after some time running.

I would be happy to provide someone with the necessary hardware who creates this code.

**Comment by OutsourcedGuru** [comment]
Mostly just subscribing to this thread but I likewise have had problems related to "insufficient gpu memory" for want of a better description. I posted in another (closed) issue #5581 for what it's worth.

* I was getting an ugly 1MB/minute memory leak from the native video library on Raspbian so I added [ffpyplayer](http://matham.github.io/ffpyplayer/installation.html) so this definitely helped (by replacing the _lossy_ `gstplayer`):

```
import os
os.environ['KIVY_VIDEO'] =              'ffpyplayer'
```

**Comment by audryste** [comment]
This pull request should fix it.
May be this pull request will fix it https://github.com/kivy/kivy/pull/6713
Also increase memory for gpu should to 512 RAM

**Comment by OutsourcedGuru** [comment]
> "Also increase memory for gpu should to 512 RAM"

For a Pi3B? It only has 1GB. I would recommend starting at 256MB, testing and raising that value until the FBOs stop, then increase it by 20% and call it a day.

**Comment by OutsourcedGuru** [comment]
Also, with respect to code changes to fix FBO exceptions, it would be really great if these simply _weren't_ raised python exceptions at all. Report a warning, return a `None` object but raising exceptions really prevent a kiosk-style application from continuing to work.

**Comment by VPetras** [comment]
> Try increasing the GPU memory. You can edit `/boot/config.txt` and append `gpu_mem=256`. More information [here](http://raspberrypi.stackexchange.com/questions/673/what-is-the-optimum-split-of-main-versus-gpu-memory)

Thanks it was helfull, i had 64MB so i switch to 256MB and its without problems. In my app was problem with rendering graph. On PC without problem but on rpi just white screen or garph withou data.

**Comment by Julian-O** [comment]
Closing this as Won't Fix, because the component in question is deprecated. See #8434.

Please let us know if you think this is in error.
