### ISSUE TITLE
Kivy kills Plasma desktop

### ISSUE THREAD

**Issue by xeroxyde** [kivy/kivy#4731]
Hello,
When I launch any program using Kivy when the window initializes it seems that my desktop environment is almost entirely closed. Every window that are already open lose their borders but remain opened. However, I can't switch between them. I can still interact with them as if everything was fine though.

Kivy was working fine several days ago, this started to happen since I've made a system upgrade and I can't determine why and where this stem from.
Does anyone had the same problem recently ?

OS: Manjaro Linux
Kernel: 4.4.31
Desktop environment: KDE
Window manager: KWin

Thank you.

**Comment by benrob0329** [comment]
I've had a similar problem in KDE Plasma as well where the desktop simply doesn't update the frame (in fact, it grabs some random frame from earlier somehow).

From what I could gather, I believe that certain application that render using OGL conflict with the compositor or general renderer of Plasma, as it also happens when I tried to use the Unreal Engine Editor.

**Comment by xeroxyde** [comment]
I thought it was more likely a problem with the SDL since its window related and it seems to be a redundant issue in Kivy development. But anyway, how is that conflict even possible ?

**Comment by tshirtman** [comment]
You could try using different window options (like fullscreen modes, borderless, etc), of kivy, to see if it influences this behavior, or try a different window provider than SDL2, you can build kivy with different providers (pygame has been the default one for a long time, and although it's deprecated, it could be useful to test with it instead, there is a X11 provider too). If you find a configuration that doesn't cause the issue, it could help finding the culprit.

**Comment by tshirtman** [comment]
Can you test with other OpenGL apps like Blender, glxgears, etc? see if it happens too, it does look more like a plasma/kwin issue than a kivy one.

**Comment by akshayaurora** [comment]
Try setting the win compositor options to not use OpenGL...does that solve the issue?

**Comment by xeroxyde** [comment]
I'm back. Sorry for the long time between my answer. I have some serious bandwidth lag since yesterday so I got some difficulties getting everything I needed.

Anyway, I tried twos programs using OpenGL, Blender and GZDoom. Both were working fine with multiple tests. I've installed kivy into a virtual environment along with pygame and it still kills the DE. I don't know and I didn't found how to launch Kwin without OpenGL. If anyone know how, I'd be glad to know.

**Comment by akshayaurora** [comment]
ok, first if you are using VirtualBox then please tell us details about that.

Open GL on Virtualbox is known to be broken and plasma5 not working with it is a known issue.

**Comment by xeroxyde** [comment]
No I'm not on a virtual machine.

**Comment by Zen-CODE** [comment]
Ha. I also have this running lubuntu 16.04 but it seems only when running fullscreen set in ~/.kivy/config.ini. Windows temporarily loose their decoration and kwin restarts. Then it's okay again. That's running 1.9.1. I think. Will experiment more and post any relevant findings. Will try and get a kwin log perhaps?

**Comment by xeroxyde** [comment]
I have more insight on the problem. It is definitly caused by a conflict between Kwin and the SDL library.
I've installed PySDL2 to develop the UI framework I need. And when I tested a simple code snippet, I had exactly the same issues I had with Kivy.

**Comment by xeroxyde** [comment]
Hello I'm back  and my problem is fixed. I'm not sure why it worked, but here is what I did.
I search and deleted every instances of the SDL library and I've reinstalled only what I needed. That's all...
Off every files I've deleted, I only haven't reinstalled the 32 bit version of the library. I guess this issue was somehow coming from them.
Anyway, thanks for your help.

**Comment by akshayaurora** [comment]
If the issue is only while going full screen. could you check disabling composition when apps go fullscreen? KDE has a option for this .

**Comment by xeroxyde** [comment]
No matter the display state, there was still the issue. But its completely fixed now.

**Comment by Zen-CODE** [comment]
For my 2c, this turned out to be a false alarm for me. My kwin crashes regularly on mint 18 :-( Not related to kivy.

**Comment by ebuenger** [comment]
In case anyone is still having issues with this, I was able to avoid the problem by running kivy in a virtual environment.
