### ISSUE TITLE
Deprecated property "<AliasProperty name=filename>" of object "<kivy.core.audio(...)>" was accessed, it will be removed in a future version

### ISSUE THREAD

**Issue by Franccisco** [kivy/kivy#6602]
### Versions

* Python: 3.7
* OS: independent
* Kivy: 1.11.1
* Kivy installation method: pip

### Description

The message displayed in title appears in the kivy logs when you load an audio using the default ```SoundLoader``` classes in ```kivy/core/audio``` files, excepting ```audio_ffpyplayer.py```. I was reading those files and realised that it happens because they are using ```self.filename``` instead of ```self.source```. As they belong to the kivy main files, the use of deprecated stuff should be replaced.

### Code and Logs
```python
from kivy.core.audio import SoundLoader

sound = SoundLoader.load('mytest.wav')
if sound:
    print("Sound found at %s" % sound.source)
    print("Sound is %.3f seconds" % sound.length)
    sound.play()
```

Example, when using SDL2:
```python
[WARNING] Deprecated property "<AliasProperty name=filename>" of object "<kivy.core.audio.audio_sdl2.SoundSDL2>" was accessed, it will be removed in a future version
```

P.S: I don't know if the deprecation warnings in ```kivy/core/audio/__init__.py``` should be removed too.

**Comment by frankgould** [comment]
I'm getting this deprecated message now. Do I need to do something to prevent it? Is it true?

**Comment by matham** [comment]
I think it may be fixed in master.

**Comment by frankgould** [comment]
I don't think so. I have buildozer.spec with entry p4a.branch = master and it generated the following message during app startup.

`[WARNING] Deprecated property "<AliasProperty name=filename>" of object "<kivy.core.audio.audio_sdl2.SoundSDL2 object at 0xddf5d1b8>" was accessed, it will be removed in a future version
`

**Comment by Franccisco** [comment]
This is fixed in kivy master branch. You said you are targetting p4a master branch, which is not the same than the kivy's.

**Comment by frankgould** [comment]
I completed a pip install and am still getting this message below in my apk startup:
[WARNING] Deprecated property "<AliasProperty name=filename>" of object "<kivy.core.audio.audio_sdl2.SoundSDL2 object at 0xdde9e2d0>" was accessed, it will be removed in a future version

**Comment by matham** [comment]
Please post the full log of the app.

**Comment by frankgould** [comment]
```
[INFO   ] Logger: Record log in /sdcard/.slideshow/logs/ss-log_20-03-26_1.txt
[INFO   ] Kivy: v1.11.1
[INFO   ] Kivy: Installed at "/data/user/0/com.android.slideshow/files/app/_python_bundle/site-packages/kivy/__init__.pyc"
[INFO   ] Python: v3.7.1 (default, Feb 29 2020, 12:56:56) 
[Clang 8.0.2 (https://android.googlesource.com/toolchain/clang 40173bab62ec7462
[INFO   ] Python: Interpreter at "android_python"
[INFO   ] Logger: Purge log fired. Analysing...
[INFO   ] Logger: Purge finished!
[INFO   ] Factory: 184 symbols loaded
[DEBUG  ] Cache: register <kv.lang> with limit=None, timeout=None
[DEBUG  ] Cache: register <kv.image> with limit=None, timeout=60
[DEBUG  ] Cache: register <kv.atlas> with limit=None, timeout=None
[INFO   ] Image: Providers: img_tex, img_dds, img_sdl2, img_gif (img_pil, img_ffpyplayer ignored)
[DEBUG  ] Cache: register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] Cache: register <kv.shader> with limit=1000, timeout=3600
[DEBUG  ] Audio: register SoundSDL2
[DEBUG  ] Audio: register MusicSDL2
[INFO   ] Audio: Providers: audio_sdl2 (audio_ffpyplayer ignored)
[INFO   ] Text: Provider: sdl2
[INFO   ] Window: Provider: sdl2
[INFO   ] GL: Using the "OpenGL ES 2" graphics system
[INFO   ] GL: Backend used <sdl2>
[INFO   ] GL: OpenGL version <b'OpenGL ES 2.0'>
[INFO   ] GL: OpenGL vendor <b'ARM'>
[INFO   ] GL: OpenGL renderer <b'Mali-400 MP'>
[INFO   ] GL: OpenGL parsed version: 2, 0
[INFO   ] GL: Texture max size <4096>
[INFO   ] GL: Texture max units <8>
[DEBUG  ] Shader: Fragment compiled successfully
[DEBUG  ] Shader: Vertex compiled successfully
[DEBUG  ] ImageSDL2: Load </data/user/0/com.android.slideshow/files/app/_python_bundle/site-packages/kivy/data/glsl/default.png>
[INFO   ] Window: auto add sdl2 input provider
[INFO   ] Window: virtual keyboard not allowed, single mode, not docked
[INFO   ] Slideshow Logging Started: Version 20.03.25, Platform:  android, Date/Time= {2020-03-26 13:06:30}
[INFO   ] SlideShow Album: Master-Pieces-L
[INFO   ] Frame Debug: True, Date/Time= {2020-03-26 13:06:30}
[DEBUG  ] App: Loading kv <./slideshow.kv>
[DEBUG  ] Wake Screen results: complete_val=b'Broadcasting: Intent { act=com.android.lcd_bl_on }\nBroadcast completed: result=0\n', complete_val=None
[DEBUG  ] ImageSDL2: Load </sdcard/.slideshow/data/pix/bootstill.png>
[INFO   ] GL: NPOT texture support is available
[WARNING] GL: Unpack subimage support is not available
[DEBUG  ] Frame Display Reported Resolution: 1920x1080
[DEBUG  ] Base: Create provider from android
[WARNING] Base: Unknown <android> provider
[INFO   ] Base: Start application main loop
[WARNING] Deprecated property "<AliasProperty name=filename>" of object "<kivy.core.audio.audio_sdl2.SoundSDL2 object at 0xdde9e308>" was accessed, it will be removed in a future version
```

**Comment by matham** [comment]
As you see in the log: `[INFO   ] Kivy: v1.11.1`.

**Comment by frankgould** [comment]
Yes. What does that mean?

**Comment by matham** [comment]
The problem should be fixed in master, but from your log it shows you're not using master but the last stable release. So you need to figure out how to use master if you want the fix.

**Comment by frankgould** [comment]
Doesn't the following command get the master you're talking about? If not, what is?

python3 -m pip install git+https://github.com/kivy/kivy.git@master

**Comment by matham** [comment]
It does assuming the environment and everything is set up correctly and it succeeds, but I guess something there is going wrong because what ran was stable and not master.

I think asking on discord for further help is probably better as it's hard to troubleshoot stuff here.

**Comment by frankgould** [comment]
Thanks @matham - I tried Inclement's suggestion `kivy==master` in my requirements from Discord yesterday and got the same results, as below (same warning for both platforms, different libraries?). I don't know what to do now other than ignore the message.

Android:
`[WARNING] Deprecated property "<AliasProperty name=filename>" of object "<kivy.core.audio.audio_sdl2.SoundSDL2 object at 0xddb1d2d0>" was accessed, it will be removed in a future version
`
RPi4B:
`[WARNING] Deprecated property "<AliasProperty name=filename>" of object "<kivy.core.audio.audio_gstplayer.SoundGstplayer object at 0xa6549270>" was accessed, it will be removed in a future version
`
