### ISSUE TITLE
MacOS scaling issue

### ISSUE THREAD

**Issue by sanderland** [kivy/kivy#6968]
**Software Versions**
* Python: 3.7.5
* OS: MacOSX
*  Kivy installation method: pip
* Kivy version: 2.0.0rc3
```
Package            Version
------------------ ---------
beautifulsoup4     4.8.1
certifi            2020.6.20
chardet            3.0.4
Cython             0.29.14
docutils           0.16
idna               2.9
importlib-metadata 1.3.0
KaTrain            1.2.2
keyring            20.0.0
Kivy               2.0.0rc3
Kivy-Garden        0.1.4
kivymd             0.104.1
lxml               4.4.2
more-itertools     8.0.2
ofxclient          2.0.3
ofxhome            0.3.3
ofxparse           0.20
Pillow             7.1.2
pip                19.3.1
pygame             1.9.6
Pygments           2.6.1
requests           2.24.0
setuptools         41.6.0
six                1.13.0
soupsieve          1.9.5
urllib3            1.25.9
wheel              0.33.6
zipp               0.6.0
```

**Describe the bug**
The entire UI shows up at half the size, but clicks are processed as if the graphics are full sized.

![image](https://user-images.githubusercontent.com/48946947/85899978-43303e00-b7ff-11ea-85ae-ed3b49697dc8.png)

**Expected behavior**
Work normally.

**To Reproduce**
Several reports on macs, single screen. No clear pattern so far.

**Comment by tshirtman** [comment]
This might have been fixed by https://github.com/kivy/kivy/pull/7293 and https://github.com/kivy/kivy/pull/7299, if you can test with kivy master.

**Comment by sanderland** [comment]
@pcorey could you check this is fixed in 1.7?

**Comment by GoBig87** [comment]
This issue still exists and I'm seeing it on osx.  I used the changes in this PR https://github.com/kivy/kivy/pull/6289/files and it almost fixed it.  I had to change https://github.com/kivy/kivy/blob/4e1fc8f2c3fd75ed6a4e2026a46417420476da6f/kivy/core/window/__init__.py#L412 this line to 
```
```
