### ISSUE TITLE
On macOS, Window size is scaled differently from widget size

### ISSUE THREAD

**Issue by probablyfine** [kivy/kivy#8140]
**Software Versions**
* Python: 3.8.9
* OS: macOS 12.6 (Apple silicon)
* Kivy: 2.1.0
* Kivy installation method: pip

**Describe the bug**
On macOS, the units for `Window` size (`kivy.core.window.Window`) seem to be twice as large as the units for widgets, and this appears to be completely independent of screen dpi/scaling: changing the screen scaling doesn't affect this behavior. Using the `kivy.metrics.dp` method also doesn't help with the issue.

**Expected behavior**
The units for Window size should be the same as the units for widget size.

**To Reproduce**
```
from kivy.core.window import Window
from kivy.app import App
from kivy.uix.boxlayout import BoxLayout
from kivy.lang import Builder

Builder.load_string(
"""
<MyWidget>
  size_hint: None, None
  size: 200, 200
  Label:
    canvas.before:
      Color:
        rgb: 0.7, 0.7, 0.7
      Rectangle:
        pos: self.pos
        size: self.size
"""
)

class MyWidget(BoxLayout):
  def __init__(self, **kwargs):
    super(MyWidget, self).__init__(**kwargs)

    # This makes the window twice as large as expected
    Window.size = self.size
    
    # Dividing the dimensions by 2 produces the "correct" size
    # Window.size = (self.size[0]/2, self.size[1]/2)

class MyApp(App):
    def build(self):
        return MyWidget()

if __name__ == '__main__':
    MyApp().run()
```

In the above code, `Window.size` is set to the same size as the main `BoxLayout`'s size, which is set in the `kv` string. This makes the window twice as large as it should be. If you uncomment the other line that first divides each `BoxLayout` dimension by 2, this produces the "correct" size window.

**Comment by matheussmoreira** [comment]
The same is occurring with me, I'll investigate what can be done.

**Comment by matheussmoreira** [comment]
For some reason this bug is not occurring with me anymore. These last days I had to change my machine (macOS version remains the same of this issue's), but maybe this problem may have been resolved by some recent update too!

**Comment by Julian-O** [comment]
@probablyfine: Given the experience of @matheussmoreira, can you please tell us if this problem disappears with the latest versions?

**Comment by probablyfine** [comment]
@Julian-O unfortunately I'm still having this problem. I made a new virtualenv (Python 3.11.6) and did a `pip install kivy` (installed v2.2.1), and then ran the minimal example I posted previously - still seeing the same behavior. I'm now on macOS 13.4.1 (same computer, M1 Pro Macbook 16 inch)

**Comment by Xovaryu** [comment]
After deciding to implement the ability to remember screen pos and size into my program I've now also run headfirst into this issue (Windows 10, window_sdl2.WindowSDL). The problem however is even more egregious than the initial post makes it appear to be.
I've been able to narrow down what happens at least somewhat. Windows has app scaling, and for big screens that would be typically around 200%, 225% for me. And this app scaling is actually applied in hindsight when setting `Window.size`.
(I've tested this by changing the scaling, and indeed with 200% if I set say a width of 500, I get 1000 instead, and with 225% if I set 500 I get as "expected" 1125 instead)
Likewise despite the Kivy default size being (800,600) the program starts at (1800, 1125). Which, okay, for a startup is okay behavior for wrong reasons. Also the external scaling causes the issue at runtime. Changing the scaling while the program is running changes the behavior too.

This then also has the "fun" consequence that even `Window.size = Window.size` does not behave like a `x=x` but rather a `x≠x` operation. At 200% scaling `Window.size = Window.size` will double the window size. Certainly not intended behavior.
This also makes setting certain resolutions impossible as `Window.size` has the input first floored to an int, and then scaled by the system scaling, then obviously inted again. So at 200% scaling no odd width/height for the window can ever be successfully set from inside the program itself.
Also `_size` will still have the originally desired resolution saved in it, so `Window.size = Window._size` or alternatively `Window._size = Window._size` do behave as `x=x` operations and do nothing just... for all the wrong reasons.

I also wandered through the Kivy code, and as expected I have not found any line of code that applies any such multiplication. I suspect hence that the issue is either that Kivy doesn't address `SDL_SetWindowSize` correctly or that there is some other Kivy-side DPI configuration issue (I had some issues in the past), or alternatively that there's some buggy/badly designed behavior outside of Kivy at work.

Either way... this is a breaking bug and I personally won't even try to implement a workaround as I have no way to test how this works in other systems, and other users may use different versions of Kivy and that workaround may break things later, it's hardly worth the hassle. But a proper analysis and fix for this would be much appreciated.

**Comment by ElliotGarbus** [comment]
@Xovaryu 
I think you will find this instructive: https://github.com/ElliotGarbus/KivyWindowSize
Let me know if you have any questions.

**Comment by Xovaryu** [comment]
@ElliotGarbus 
Unfortunately I can't say that I find this instructive in a way that makes me not think this is a big issue at least.
As mentioned I work with Windows 10 and suspect that this is a crossplatform issue.
Furthermore `Metrics.density` is one of the first things I tested and it does definitely not apply to `Window.size` for me whatsoever. Despite this not really being necessary again I just tested this with `Metrics.density = 0.1` and no this has no effect. Scaling directly takes the current system scale into account, meaning it is dependent on this external variable.
And if that really works differently like that... that seems like a strange pitfall for developers. I see no good reason why density should apply to window sizing in one OS but not another. Especially not in a way that not just makes a `x=x` operation actually change anything, which I think it **never** should, but then additionally in different ways too. I've seen no indication of such behavior in the official documentation either.

I think that kind of behavior is an issue regardless of context, as for instance opening a side panel that should just quietly add it's own width to window size now can't simply do `Window.size = (Window.size[0] + y, Window.size[1])` but instead would require additional logic, and in case of density or even other things applying would require entire code blocks.
(This isn't even my use case, I have 0 need for actual dynamic runtime window size adjustments.)

**Comment by misl6** [comment]
If we have an undocumented behavior to break, this is the right moment to do so, as we're working on a major release (`3.0.0`).

I will keep this issue monitored for updates.

**Comment by Xovaryu** [comment]
> @Xovaryu The code provided is a solution for saving and restoring Window position. Did it not work for you?

No. The problem is just a fundamental level deeper than anything your code does. `Window.size = Window.size` itself is broken. The entire size handling is broken to the point that technically speaking this problem manifests with 0 lines of code on my side because kivy doesn't even apply its own resolution from the .kivy/config.ini correctly.

**Comment by ElliotGarbus** [comment]
I just ran the code on WIndows11 and is saves and restores with Window size and pos. Are you seeing something different?
I don't understand your concern. 

When saving the Window size to the config, divide by Metrics.density.  When loading the config use the saved value.
```
    def window_request_close(self, win):
        # Window.size is automatically adjusted for density, must divide by density when saving size
        print('Window close requested')
        config = self.config
        config.set('Window', 'width', int(Window.size[0]/Metrics.density))
        config.set('Window', 'height', int(Window.size[1]/Metrics.density))
        config.set('Window', 'top', Window.top)
        config.set('Window', 'left', Window.left)
        print(f'close: Window.size: {Window.size}')
        print(f'close: Window.top: {Window.top}, Window.left: {Window.left}')
        return False
```
...and here is the size being set when the app opens.
```
    def on_start(self):
        # Set Window to previous size and position
        config = self.config
        width = config.getdefault('Window', 'width', 300)
        height = config.getdefault('Window', 'height', 200)
        Window.size = (int(width), int(height))
        Window.top = int(config.getdefault('Window', 'top', 40))
        Window.left = int(config.getdefault('Window', 'left', 40))
```

**Comment by Xovaryu** [comment]
@ElliotGarbus I've already answered all of those questions in my previous posts:
> Are you seeing something different?

Completely different. Yes I have used your exact `on_start` code block, and yes when doing that I still end up with a window size that is multiplied by my system scale, not `Metrics.density`.
> When saving the Window size to the config, divide by Metrics.density.

I mentioned before:
> Despite this not really being necessary again I just tested this with Metrics.density = 0.1 and no this has no effect.

It's not `Metrics.density`, really, I promise, it isn't. I also use `Metrics.density = 1` for my application so even if it would apply in my OS(W10)/Kivy(2.3.0)/Python(3.10) configuration, which it does not, a division by 1 is just as much an identity function as `Window.size = Window.size` should be. Which it isn't, which is the breaking bug we're talking about.

The original poster has put it well:
> **Expected behavior**
> The units for Window size should be the same as the units for widget size.

Which it definitionally can not be when for whatever reasons `Metrics.density` or system scaling is applied to the `Window.size` values after setting those but not other `.size` values. `Metrics.density` or system scaling or any other factors have no (direct) business with `Window.size`.

Also the necessity of `config.set('Window', 'width', int(Window.size[0]/Metrics.density))` is at best bad design/oversight on the part of some developer (which may happen, I think we've all been there and I sure know I have been), and at worst an accidentally introduced bug. It is also definitely not expected behavior.
_If your code works for you, that is a problem, not a solution._

And the fact that the code you posted works for you, but not for me really just makes the problem even worse because that means not just are we talking about the bug of `Window.size = Window.size` not acting like an identity function should (which is to do nothing), and it's not only behavior that is broken in different ways between different types of OSs, but it's even broken in different ways between different Windows versions, assuming this isn't actually down to a different Kivy/Python version (which would still only shift where the problem is, not whether or not there is a problem).

Either way, I agree with misl6, to me this definitely seems like an issue that needs to be tackled for a major release, because fixing it will cause numerous hacky solutions like `config.set('Window', 'width', int(Window.size[0]/Metrics.density))` that shouldn't have been needed to break.

**Comment by Julian-O** [comment]
[Note: I am not familiar with the various screen density and app scaling issues. This is generic advice.]

@Xovaryu: If you are so inclined, this would be a perfect space to propose what a solution should look like. When we set the Windows.size to (400, 600) what should we see? Should there be a place to find the size adjusted for density and scaling?

In an ideal world, I would suggest writing some unit tests that fail now but would pass when it worked, but I am not sure how you would programmatically detect the number of pixels a window *actually* was. I assume there is a way, but I don't know it.

**Comment by ElliotGarbus** [comment]
@Xovaryu 
Metrics.desity is set by the system, it matches the scale factor set in Windows settings.  I don't understand what you are trying to achieve by setting the density.  In the code I provided, When I set the window size in the app, and close the app.  The size and position is restored when the app is next launched.  To use enter the desired window size, then press the appropriate button.  Then close the app.  When the app relaunches the size and pos will be restored.

If this is not working for you I would be very interested as to why.  I have shipped a number of apps across Windows and Mac and have not had any issues with this working correctly. 

I've focused on saving/restoring window size and pos with the current implementation.

**Comment by Xovaryu** [comment]
@Julian-O Sure, I am so inclined.
For that I need to reach back on the structure I observe currently.
* `Window.size` when read out returns the correct and expected values of the window as it is. My screen has a width of 3840, and the app at full screen will report exactly that value
* As far as I could glean from this repo `.size` works with a specific get function, `_get_size`, which in turn calls `_get_gl_size` which calls `SDL_GL_GetDrawableSize`. This I would reckon is to make sure that whenever `Window.size` is read, it returns the current actual exact size of the window, no matter how the window arrived at that size.
* `Window._size` does not do that. It reports to my knowledge the last value that was put in raw. As such these two can be different. This seems to be a hidden variant used for checks like the one here: `if self._size != size:` in https://github.com/kivy/kivy/blob/master/kivy/core/window/__init__.py#L432
* Setting either `Window.size` or `Window._size` shows the exact same behavior, which in my case is that the window size will be set to the specified size, multiplied by the current system scaling, at runtime. For other systems that seems to be `Metrics.density`.

> When we set the Windows.size to (400, 600) what should we see?

Given that `Window.size` gets its values as outlined above and those are exact on-screen pixel values, then setting `Window.size` should also set exact on-screen pixel values. So precisely a width of 400 pixels, and a height of 600, regardless of any and all other variables. Executing a self-assignment like `Window.size = Window.size` should always do nothing. Likewise anything like `Widget.size = Window.size` or `Window.size = Widget.size` should always end up with that widget and the window also having the same size.

> Should there be a place to find the size adjusted for density and scaling?

I would think so. Having a default setting apply together with system scaling isn't a bad idea either, but then this should be done explicitly. Further as it currently stands `Metrics.density` is linked to system scaling, and even tracks it as I figured out, but stops tracking, obviously, when the user manually sets a value, which is fine. But if users can, by design, disentangle that value, then of course there even more can't be any implicit but forced additional factors introduced into window scaling since this then causes another extra schism.
I could also imagine having a function to explicitly set window size while taking current system scaling or `Metrics.density` into account (which are the same until a program redefines `Metrics.density` for which there are valid uses).

> In an ideal world, I would suggest writing some unit tests that fail now but would pass when it worked, but I am not sure how you would programmatically detect the number of pixels a window actually was. I assume there is a way, but I don't know it.

I don't think we need to make it so complicated on ourselves. This here is sufficient.
```python
w1 = Window.size
Window.size = Window.size
EventLoop.idle()
w2 = Window.size
print(w1 == w2) # Should always be true, but as it stands will be false for many systems
```
It's just the most basic implementation of a simple check to see that x=x didn't actually change anything, as it shouldn't. `EventLoop.idle()` is just necessary to make sure the resizing finishes before getting the new resolution, lest this would return most likely as the resizing hasn't finished by the time we read the value out again.

@ElliotGarbus
> I don't understand what you are trying to achieve by setting the density.

Scaling independent minimalist precise placement of UI elements. I have a need for a lot of UI elements on screen all at once, and limited ability to test on all devices. I am not perfectly happy with this solution and have been planning better routes, and I was intending to refactor this behavior eventually and I may then also either give `Metrics.density` back to the system, or have it manually adjustable in app, or yet another solution. But for now this solution works very well for me. It's a simple way to make sure that the UI looks the exact same on all devices.

> I've focused on saving/restoring window size and pos with the current implementation.

I get that and I don't doubt that this works. But your current implementation is a workaround for a pretty dreadful bug, or highly unusual and unexpected behavior at best. For good coding and intuitive behavior self-assignments mustn't drag in external variables. Never.
Also, again. The fact that `Metrics.density` is dragged into window sizing like this breaks a lot of stuff. It makes some finer resolutions impossible to ever apply (which admittedly is still kind of a minor concern), and it makes appropriate scaling of widgets and windows relative to one another at best a lot more complicated, and at worst due to the forced rounding imprecision may cause additional issues (which is not a minor concern imo).
And I just did the math... and yeah. Using then a widget that needs to grow and shrink the window will introduce rounding errors and cause a gradual resolution drift because the values are floored, multiplied and floored again. This will shrink windows.

**Comment by Xovaryu** [comment]
And... yup. I decided to quickly also apply the math from above.
```python
Window.size = ((Window.size[0]+24)/2.25, Window.size[1]/2.25)
EventLoop.idle()
Window.size = ((Window.size[0]-24)/2.25, Window.size[1]/2.25)
EventLoop.idle()
print(Window.size)
```
This, on my system, will shrink the window a little with each execution. Not so great.

**Comment by misl6** [comment]
Hi everyone,

Please check PR:  https://github.com/kivy/kivy/pull/8630

**Comment by misl6** [comment]
PR #8630 has been merged, therefore this issue can be closed.

BTW, please check the discussion on #8630, as even if it's been fixed, setting `Window.size` for setting the window size on the display is discouraged.

See:
https://kivy.org/doc/master/api-kivy.core.window.html#kivy.core.window.WindowBase.size and https://kivy.org/doc/master/api-kivy.core.window.html#kivy.core.window.WindowBase.system_size
