### ISSUE TITLE
Scrollview Continues Scrolling After Dragging Stops When Mouse Moves Over It

### ISSUE THREAD

**Issue by pybeginnerdev** [kivy/kivy#9052]
**Description of Bug**:

I'm encountering an issue with `ScrollView` where it continues to scroll after dragging stops (i.e., after `on_touch_up` is called) if the mouse moves over the `ScrollView` area, even when `on_touch_move` returns `False`. This behavior persists in both Kivy 2.2.1 and 2.3.1, suggesting it may be a long-standing bug or an unintended feature of `ScrollView`.

**Expected Behavior**:
- The `ScrollView` should not scroll after dragging stops (i.e., when `dragging=False` and `on_touch_move` returns `False`).

**Actual Behavior**:
- The `ScrollView` continues to scroll as the mouse moves over it, even though `on_touch_move` returns `False` and no touch is active.
- This happens even when the scroll effect is set to `ScrollEffect` (no momentum) and velocities are manually reset to 0.

**Steps to Reproduce**:
1. Create a Kivy app with a custom `ScrollView` class that overrides `on_touch_down`, `on_touch_move`, and `on_touch_up` to track dragging state.
2. Set up the `ScrollView` to allow scrolling only when `dragging=True` (set to `True` on `on_touch_down`, `False` on `on_touch_up`).
3. In `on_touch_move`, return `True` only if `dragging=True`; otherwise, return `False`.
4. Run the app, drag the `ScrollView` (e.g., with a left mouse click and drag), and release.
5. Move the mouse over the `ScrollView` without clicking.

**Minimal Reproducible Example**:
```python
from [kivy.app](http://kivy.app/) import App
from kivy.uix.scrollview import ScrollView
from kivy.uix.label import Label
from kivy.uix.floatlayout import FloatLayout
from kivy.properties import BooleanProperty
from kivy.logger import Logger
from kivy.effects.scroll import ScrollEffect

class CustomScrollView(ScrollView):
    dragging = BooleanProperty(False)

    def __init__(self, **kwargs):
        super(CustomScrollView, self).__init__(**kwargs)
        self.effect_x = ScrollEffect()
        self.effect_y = ScrollEffect()
        Logger.info("CustomScrollView: Scroll effects set to basic ScrollEffect")

    def on_touch_down(self, touch):
        if 'button' in touch.profile and touch.button in ('scrollup', 'scrolldown', 'scrollleft', 'scrollright'):
            Logger.info("CustomScrollView: Blocking mouse scroll wheel event")
            return False
        ret = super(CustomScrollView, self).on_touch_down(touch)
        if ret and self.collide_point(*touch.pos) and not touch.grab_current:
            self.dragging = True
            Logger.info(f"CustomScrollView: Dragging started, dragging={self.dragging}")
        return ret

    def on_touch_move(self, touch):
        if 'button' in touch.profile and touch.button == 'left' and not self.dragging:
            Logger.info("CustomScrollView: Ignoring mouse movement without drag")
            return False
        ret = super(CustomScrollView, self).on_touch_move(touch)
        Logger.info(f"CustomScrollView: on_touch_move - ret={ret}, pos={touch.pos}, dragging={self.dragging}, grab_current={touch.grab_current}, effect_x_velocity={self.effect_x.velocity if self.effect_x else 0}")
        if ret and self.collide_point(*touch.pos) and not touch.grab_current and self.dragging:
            Logger.info(f"CustomScrollView: Allowing scroll, dragging={self.dragging}")
            return True
        self.stop_scroll()
        return False

    def on_touch_up(self, touch):
        if self.dragging:
            self.dragging = False
            self.stop_scroll()
            Logger.info(f"CustomScrollView: Dragging stopped, dragging={self.dragging}, effect_x_velocity={self.effect_x.velocity if self.effect_x else 0}")
        return super(CustomScrollView, self).on_touch_up(touch)

    def stop_scroll(self):
        if self.effect_x:
            self.effect_x.velocity = 0
        if self.effect_y:
            self.effect_y.velocity = 0
        Logger.info("CustomScrollView: Scroll stopped manually")

class TestApp(App):
    def build(self):
        layout = FloatLayout(size=(800, 600))
        scroll_view = CustomScrollView(size_hint=(1, 1), pos_hint={'center_x': 0.5, 'center_y': 0.5})
        content = FloatLayout(size=(800, 2000))  # Large content to enable scrolling
        label = Label(text="Scroll Me\n" * 100, size_hint=(None, None), size=(800, 2000))
        content.add_widget(label)
        scroll_view.add_widget(content)
        layout.add_widget(scroll_view)
        return layout

if __name__ == '__main__':
    TestApp().run()
```
**Software Versions**
* Python: 3.10.12
* OS: Ubuntu 22.04
* Kivy: 2.21 and 2.3.1
* Kivy installation method: pip
* Graphics: OpenGL 4.5 (Mesa 23.2.1, AMD KABINI)

**Additional context**:

•  The issue persists even when scroll effects are set to ScrollEffect (no momentum).
•  Manually resetting effect_x.velocity and effect_y.velocity to 0 does not stop the scrolling.
•  Blocking mouse scroll wheel events and filtering mouse movement in on_touch_move does not resolve the issue.
•  Logs confirm that on_touch_move returns False when dragging=False, yet scrolling continues.

**Possible Cause**:

•  ScrollView may be interpreting mouse movement as a scroll gesture after a drag, even when on_touch_move returns False.
•  There might be an internal state in ScrollView that isn’t properly reset after dragging stops.

**Suggested Fix**:

•  Ensure ScrollView respects the return value of on_touch_move and stops all scrolling when False is returned.
•  Investigate whether mouse movement is being treated as a scroll gesture internally and provide a way to disable this behavior.

NOTE: If anyone needs copies of my specific code where I'm encountering this issue please ask and I will provide.

Thanks in advance for any help.

**Comment by ElliotGarbus** [comment]
Looking closer at your code it looks like you want to block mouse scrolling, and stop scrolling after the finger is lifted up.  I've implemented this in the code below.  I'm going to mark this as a support issue.  If you have questions I suggest you the kivy support channels.  

If you want to more generally intercept the touches going to the ScrollView, Intercept the touches of the parent class, (here a FloaLayout).  The ScrollView has complex touch handling to determine if a drag has happened. 

I hope this helps:

```python
from kivy.app import App
from kivy.lang import Builder
from kivy.loader import Logger
from kivy.uix.scrollview import ScrollView
from kivy.clock import Clock

kv = """
<ScrollLabel@Label>:
    text: "Scroll Me\\n" * 100
    size_hint_y: None
    height: self.texture_size[1]
    
FloatLayout:
    CustomScrollView:
        ScrollLabel:
"""


class CustomScrollView(ScrollView):
    def on_touch_down(self, touch):
        # filters out scroll touches
        if self.collide_point(*touch.pos) and 'button' in touch.profile and \
                touch.button in ('scrollup', 'scrolldown', 'scrollleft', 'scrollright'):
            Logger.info("Blocking mouse scroll wheel event")
            return False
        return super().on_touch_down(touch)

    def on_scroll_start(self, touch):
        Logger.info('Scroll Started')
        super().on_scroll_start(touch)

    def on_scroll_stop(self, touch):
        Logger.info('Scroll stopped')
        super().on_scroll_stop(touch)
        Clock.schedule_once(self.stop_scroll, .2)  # Allow the scroll, then stop it

    def stop_scroll(self, dt):
        self.effect_y.velocity = 0
        Logger.info('effect stop')


class TestApp(App):
    def build(self):
        return Builder.load_string(kv)


if __name__ == '__main__':
    TestApp().run()
```

**Comment by pybeginnerdev** [comment]
Thank you Elliot! This was invaluably helpful to resolve the mouse scrolling issues, I'm still having issues with the touchpad scrolling but it's relieving to know its not an actual bug in the Kivy software as I thought it was.

I'll look for information on the internal workings of the ScrollView widget to intercept and address the touchpad issues (block dragging without touch scrolling & one-finger touch scrolling, and unblock two-finger touch scrolling) and if I can't resolve it on my own I'll use the Kivy support channels as referred. Additionally I'll exercise more caution before reporting a potential bug.

Regardless, I am very grateful for your help in getting me moving with this issue I wasn't getting anywhere with despite my misunderstanding of the cause of the issue (thinking it was an issue with Kivy).
